// Typed form definitions from the frozen Employee API contract, 2026-09-20.
// Financial values remain decimal strings; no formula is evaluated on the client.
const employeeActionFields = <String, List<Map<String, Object?>>>{
  "accounting_prepare": [
    {
      "name": "preparation_kind",
      "kind": "choice",
      "required": true,
      "options": ["journal", "reconciliation"],
    },
    {
      "name": "description",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {"name": "as_of", "kind": "date", "required": true},
    {
      "name": "evidence",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {"name": "lines", "kind": "lines", "required": false, "maxItems": 100},
    {
      "name": "statement_balance",
      "kind": "money",
      "required": false,
      "signed": false,
    },
    {
      "name": "ledger_balance",
      "kind": "money",
      "required": false,
      "signed": false,
    },
  ],
  "advance_decide": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "decision",
      "kind": "choice",
      "required": true,
      "options": ["approved", "rejected"],
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "advance_disburse": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "occurred_at", "kind": "timestamp", "required": true},
    {
      "name": "payment_method",
      "kind": "choice",
      "required": true,
      "options": ["cash", "gcash", "bank"],
    },
    {
      "name": "reference",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "settlement_evidence",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "employee_acknowledgment",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "advance_repay": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "amount", "kind": "money", "required": true, "signed": false},
    {"name": "occurred_at", "kind": "timestamp", "required": true},
    {
      "name": "reference",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "settlement_evidence",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "advance_request": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "amount", "kind": "money", "required": true, "signed": false},
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "installments",
      "kind": "installments",
      "required": true,
      "minItems": 1,
      "maxItems": 104,
    },
    {
      "name": "employee_acknowledgment",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "payroll_authorization",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "advance_terms": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "installments",
      "kind": "installments",
      "required": true,
      "minItems": 1,
      "maxItems": 104,
    },
    {
      "name": "employee_acknowledgment",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "payroll_authorization",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "attendance_record": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "event_type",
      "kind": "choice",
      "required": true,
      "options": ["clock_in", "break_start", "break_end", "clock_out"],
    },
    {"name": "captured_at", "kind": "timestamp", "required": true},
    {"name": "device_id", "kind": "record", "required": true},
    {"name": "previous_event_id", "kind": "record", "required": true},
    {"name": "sequence", "kind": "integer", "required": true, "minimum": 1},
    {"name": "offline", "kind": "bool", "required": true},
  ],
  "backup_save": [
    {"name": "user_id", "kind": "employee", "required": true},
    {"name": "starts_on", "kind": "date", "required": true},
    {"name": "ends_on", "kind": "date", "required": true},
    {
      "name": "duties",
      "kind": "duties",
      "required": true,
      "options": [
        "review_requests",
        "approve_payroll",
        "approve_advances",
        "assign_tasks",
        "prepare_payroll",
      ],
      "maxItems": 5,
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "calendar_save": [
    {"name": "work_date", "kind": "date", "required": true},
    {
      "name": "day_kind",
      "kind": "choice",
      "required": true,
      "options": [
        "ordinary",
        "special_working",
        "special_nonworking",
        "regular_holiday",
        "double_regular_holiday",
      ],
    },
    {
      "name": "source",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "correction_request": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "work_date", "kind": "date", "required": true},
    {"name": "clock_in", "kind": "timestamp", "required": true},
    {"name": "clock_out", "kind": "timestamp", "required": true},
    {
      "name": "unpaid_break_minutes",
      "kind": "integer",
      "required": true,
      "minimum": 0,
      "maximum": 1440,
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "leave_balance_adjust": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "as_of", "kind": "date", "required": true},
    {
      "name": "minutes",
      "kind": "integer",
      "required": true,
      "minimum": -1000000,
      "maximum": 1000000,
    },
    {
      "name": "kind",
      "kind": "choice",
      "required": true,
      "options": ["opening", "correction"],
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "leave_conversion_request": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "as_of", "kind": "date", "required": true},
    {
      "name": "minutes",
      "kind": "integer",
      "required": true,
      "minimum": 0,
      "maximum": 1000000,
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "leave_request": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "work_date", "kind": "date", "required": true},
    {
      "name": "minutes",
      "kind": "integer",
      "required": true,
      "minimum": 0,
      "maximum": 1440,
    },
    {
      "name": "leave_kind",
      "kind": "choice",
      "required": true,
      "options": [
        "ordinary",
        "maternity",
        "paternity",
        "solo_parent",
        "vawc",
        "special_women",
        "unpaid",
      ],
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "eligibility_evidence",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
  ],
  "overtime_request": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "work_date", "kind": "date", "required": true},
    {
      "name": "minutes",
      "kind": "integer",
      "required": true,
      "minimum": 0,
      "maximum": 1440,
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "payroll_adjustment": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "original_payroll_id", "kind": "record", "required": true},
    {
      "name": "component",
      "kind": "choice",
      "required": true,
      "options": [
        "basic_pay",
        "leave_pay",
        "overtime",
        "premium_pay",
        "performance_benefit",
        "tax",
        "statutory",
        "advance_repayment",
        "lawful_recovery",
        "other",
      ],
    },
    {"name": "amount", "kind": "money", "required": true, "signed": true},
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "lawful_basis",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "responsibility_evidence",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "employee_response",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "maximum_authorized_recovery",
      "kind": "money",
      "required": false,
      "signed": false,
    },
    {"name": "shortage_id", "kind": "record", "required": false},
  ],
  "payroll_approve": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "decision",
      "kind": "choice",
      "required": true,
      "options": ["approved", "rejected"],
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "payroll_payment": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "amount", "kind": "money", "required": true, "signed": false},
    {"name": "occurred_at", "kind": "timestamp", "required": true},
    {
      "name": "payment_method",
      "kind": "choice",
      "required": true,
      "options": ["cash", "gcash", "bank"],
    },
    {
      "name": "reference",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "settlement_evidence",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "employee_acknowledgment",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "result",
      "kind": "choice",
      "required": true,
      "options": ["completed", "pending", "failed"],
    },
  ],
  "payroll_prepare": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "week_start", "kind": "date", "required": true},
    {
      "name": "payroll_kind",
      "kind": "choice",
      "required": false,
      "options": [
        "weekly",
        "thirteenth_month",
        "separation",
        "leave_conversion",
      ],
      "default": "weekly",
    },
    {
      "name": "leave_conversion_request_id",
      "kind": "record",
      "required": false,
    },
    {
      "name": "withholding_override",
      "kind": "money",
      "required": false,
      "signed": false,
    },
    {
      "name": "withholding_basis",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "unworked_holiday_dates",
      "kind": "dates",
      "required": false,
      "maxItems": 7,
    },
    {
      "name": "unworked_holiday_basis",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "profile_save": [
    {
      "name": "ordinary_leave_days_per_year",
      "kind": "integer",
      "required": false,
      "minimum": 5,
      "maximum": 365,
    },
    {"name": "leave_eligible_from", "kind": "date", "required": false},
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "hire_date", "kind": "date", "required": true},
    {"name": "effective_from", "kind": "date", "required": true},
    {"name": "daily_rate", "kind": "money", "required": true, "signed": false},
    {
      "name": "payout_method",
      "kind": "choice",
      "required": true,
      "options": ["cash", "gcash", "bank"],
    },
    {"name": "staff_manager", "kind": "bool", "required": true},
    {"name": "active", "kind": "bool", "required": true},
    {"name": "premium_pay_covered", "kind": "bool", "required": true},
    {"name": "holiday_pay_covered", "kind": "bool", "required": true},
    {"name": "tax_exempt", "kind": "bool", "required": true},
    {
      "name": "gp_partial_day_policy",
      "kind": "choice",
      "required": true,
      "options": ["prorated", "full_day"],
    },
    {
      "name": "classification_basis",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "request_decide": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "decision",
      "kind": "choice",
      "required": true,
      "options": ["approved", "rejected", "cancelled"],
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "paid_minutes",
      "kind": "integer",
      "required": false,
      "minimum": 0,
      "maximum": 1440,
    },
  ],
  "schedule_save": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "effective_from", "kind": "date", "required": true},
    {
      "name": "work_days",
      "kind": "days",
      "required": true,
      "minItems": 1,
      "maxItems": 6,
    },
    {"name": "start_time", "kind": "time", "required": true},
    {"name": "end_time", "kind": "time", "required": true},
    {
      "name": "meal_minutes",
      "kind": "integer",
      "required": true,
      "minimum": 0,
      "maximum": 1440,
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "shift_request": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "effective_from", "kind": "date", "required": true},
    {
      "name": "work_days",
      "kind": "days",
      "required": true,
      "minItems": 1,
      "maxItems": 6,
    },
    {"name": "start_time", "kind": "time", "required": true},
    {"name": "end_time", "kind": "time", "required": true},
    {
      "name": "meal_minutes",
      "kind": "integer",
      "required": true,
      "minimum": 0,
      "maximum": 1440,
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "shortage_decide": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "decision",
      "kind": "choice",
      "required": true,
      "options": ["confirmed", "dismissed", "reversed"],
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "response_opportunity",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "shortage_report": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "work_date", "kind": "date", "required": true},
    {
      "name": "expected_cash",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "accounted_cash",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "evidence",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "shortage_respond": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "explanation",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "statutory_month_save": [
    {"name": "prior_employee_deductions", "kind": "money", "required": false},
    {"name": "employee_id", "kind": "employee", "required": true},
    {"name": "month", "kind": "date", "required": true},
    {
      "name": "sss_employee",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "sss_employer",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "philhealth_employee",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "philhealth_employer",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "pagibig_employee",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "pagibig_employer",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "employer_other",
      "kind": "money",
      "required": true,
      "signed": false,
    },
    {
      "name": "compensation_basis",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "source",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "statutory_remittance": [
    {"name": "month", "kind": "date", "required": true},
    {
      "name": "agency",
      "kind": "choice",
      "required": true,
      "options": ["sss", "philhealth", "pagibig", "bir"],
    },
    {"name": "amount", "kind": "money", "required": true, "signed": false},
    {"name": "occurred_at", "kind": "timestamp", "required": true},
    {
      "name": "reference",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {
      "name": "settlement_evidence",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "task_progress": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "status",
      "kind": "choice",
      "required": true,
      "options": ["todo", "in_progress", "done", "cancelled"],
    },
    {
      "name": "reason",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
  ],
  "task_save": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "description",
      "kind": "text",
      "required": true,
      "minLength": 1,
      "maxLength": 2000,
    },
    {"name": "due_date", "kind": "date", "required": true},
    {
      "name": "notes",
      "kind": "text",
      "required": false,
      "maxLength": 2000,
      "default": "",
    },
    {"name": "related_client_id", "kind": "record", "required": false},
    {"name": "related_application_id", "kind": "record", "required": false},
  ],
  "payroll_history_import": [
    {"name": "employee_id", "kind": "employee", "required": true},
    {
      "name": "year",
      "kind": "integer",
      "required": true,
      "minimum": 2000,
      "maximum": 2200,
    },
    {"name": "through_date", "kind": "date", "required": true},
    {"name": "basic_earned", "kind": "money", "required": true},
    {"name": "taxable_earned", "kind": "money", "required": true},
    {"name": "tax_withheld", "kind": "money", "required": true},
    {"name": "thirteenth_paid", "kind": "money", "required": true},
    {"name": "other_benefits_paid", "kind": "money", "required": true},
    {"name": "source", "kind": "text", "required": true, "maxLength": 2000},
  ],
};
