import test from 'node:test';import assert from 'node:assert/strict';import {Element,fire} from './helpers/dom.mjs';
const {mountClientWorkspace}=await import(process.env.CLIENT_BASELINE?'../assets/roles/client-baseline.js':'../assets/roles/client.js');
const tick=()=>new Promise(r=>setTimeout(r,0));
function decorate(node,parent=null,doc=Object.assign(new EventTarget(),{body:{}})){node.parentElement=parent;node.isConnected=true;node.ownerDocument=doc;node.dataset=Object.fromEntries(Object.entries(node.attributes).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),v]));for(const child of node.children)if(typeof child!=='string')decorate(child,node,doc);return doc;}
for(const edited of [false,true])test(`support save retains renewal and proof File node, later typed input ${edited}`,async t=>{
 const prev=globalThis.FormData;globalThis.FormData=class{constructor(f){this.f=f;}get(name){return this.f.querySelector(`[name="${name}"]`)?.value;}};t.after(()=>globalThis.FormData=prev);
 const root=new Element();const query=root.querySelectorAll.bind(root);root.querySelectorAll=selector=>{const pair=selector.match(/^(\[[^\]]+\])(\[[^\]]+\])$/);return pair?query(pair[1]).filter(n=>n.getAttribute(pair[2].slice(1,-1))!==null):query(selector);};let finish,submitted;const controller=new AbortController();t.after(()=>controller.abort());let failRefresh=false;
 const api={request:async(path,options={})=>{if(options.method){submitted=options.body;return new Promise(r=>finish=r);}if(path==='/api/v1/client/loans')return {loans:[]};if(path.includes('payment-proofs'))return {proofs:[],capability:{upload_available:true,max_bytes:10485760}};if(path.endsWith('/support')&&failRefresh)throw Error('read failed');if(path.includes('notifications'))return [];if(path.endsWith('/renewals'))return {loans:[],requests:[]};if(path.endsWith('/payments'))return {payments:[]};return {requests:[]};}};
 const context={root,api,signal:controller.signal,setNavigation(){}};await mountClientWorkspace(context);await tick();await tick();decorate(root);
 const form=root.querySelector('#client-support-form'),renewal=root.querySelector('#client-renewal-form');renewal.querySelector('[name="requestedAmount"]').value='5000';renewal.querySelector('[name="message"]').value='Renewal draft';form.querySelector('[name="category"]').value='payment';form.querySelector('[name="subject"]').value='Question';form.querySelector('[name="message"]').value='Submitted question';const file=root.querySelector('[name="proofFile"]');const chosen=new Blob(['synthetic'],{type:'image/png'});file.files=[chosen];root.querySelector('[name="note"]').value='Proof draft';fire(form,'submit');if(edited)form.querySelector('[name="message"]').value='Later typing';failRefresh=true;finish({request:{request_id:'40000000-0000-4000-8000-000000000001',client_id:'50000000-0000-4000-8000-000000000001',created_at:'2026-10-02T01:00:00Z',status:'open',...submitted}});await tick();await tick();
 assert.ok(root.querySelector('#client-support-form')===form,'support node retained');assert.equal(root.querySelector('#client-renewal-form'),renewal);assert.equal(root.querySelector('[name="proofFile"]'),file);assert.equal(file.files[0],chosen);assert.equal(renewal.querySelector('[name="requestedAmount"]').value,'5000');assert.equal(form.querySelector('[name="message"]').value,edited?'Later typing':'');assert.match(root.querySelector('[data-client-region="support"]').textContent,/unavailable/);
});


