import test from 'node:test';import assert from 'node:assert/strict';
import {Element,fire} from './helpers/dom.mjs';
import {mountClientWorkspace,requestClientRenewalCashConfirmation} from '../assets/roles/client.js';
const tick=()=>new Promise(r=>setTimeout(r,5));
function decorate(node,parent=null,doc=Object.assign(new EventTarget(),{body:{}})){node.parentElement=parent;node.isConnected=true;node.ownerDocument=doc;node.dataset=Object.fromEntries(Object.entries(node.attributes).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),v]));for(const child of node.children)if(typeof child!=='string')decorate(child,node,doc);return doc;}
async function harness(t,{mutation=()=>({}),renewals={loans:[{loan_id:'loan',loan_number:'LN',eligible:true}],requests:[]},notifications=[]}={}){const prev=globalThis.FormData;globalThis.FormData=class{constructor(f){this.f=f;}get(name){return this.f.querySelector(`[name="${name}"]`)?.value;}};t.after(()=>globalThis.FormData=prev);const root=new Element();const query=root.querySelectorAll.bind(root);root.querySelectorAll=selector=>{const pair=selector.match(/^(\[[^\]]+\])(\[[^\]]+\])$/);return pair?query(pair[1]).filter(n=>n.getAttribute(pair[2].slice(1,-1))!==null):query(selector);};let handle;const calls=[];const controller=new AbortController();t.after(()=>controller.abort());const api={request:async(path,options={})=>{calls.push({path,options});if(options.method)return mutation(path,options);if(path.endsWith('/loans'))return {loans:[]};if(path.endsWith('/renewals'))return renewals;if(path.endsWith('/payments'))return {payments:[]};if(path.endsWith('/activity-notifications'))return notifications;if(path.endsWith('/account'))return {profile:{}};return {requests:[]};}};const session={user:{id:'owner'}};const context={root,api,session,getSession:()=>session,signal:controller.signal,setNavigation(){},registerWorkspaceHandle:h=>handle=h};await mountClientWorkspace(context);await tick();decorate(root);return {root,calls,context,get handle(){return handle;},decorate:()=>decorate(root)};}
test('header refresh must not reopen a pending renewal submission',async t=>{let posts=0;const h=await harness(t,{mutation:()=>{posts++;return new Promise(()=>{});}});await h.handle.activate('client-renewals');await tick();h.decorate();const form=h.root.querySelector('#client-renewal-form');form.querySelector('[name="loanId"]').value='loan';form.querySelector('[name="requestedAmount"]').value='5000';form.querySelector('button[type="submit"]').disabled=false;fire(form,'submit');await tick();assert.equal(posts,1);await h.handle.refreshVisible();fire(form,'submit');await tick();assert.equal(posts,1,'ordinary refresh must not authorize a second in-flight POST');});
test('resolved malformed Support result must not clear a draft as verified saved',async t=>{const h=await harness(t,{mutation:()=>({})});await h.handle.activate('client-support');h.decorate();const form=h.root.querySelector('#client-support-form');form.querySelector('[name="subject"]').value='Question';form.querySelector('[name="message"]').value='Retain unconfirmed text';fire(form,'submit');await tick();assert.equal(form.querySelector('[name="message"]').value,'Retain unconfirmed text');});
test('cash-confirm helper must not accept empty resolved response as success',async()=>{await assert.rejects(requestClientRenewalCashConfirmation({api:{request:async()=>({})},requestId:'request',confirmAction:()=>true}),error=>error.code==='client_result_unverified');});
test('notification read must match the current recipient',async t=>{const note={notification_id:'note',recipient_user_id:'owner',notification_type:'unknown',is_read:false};const h=await harness(t,{notifications:[note],mutation:()=>({...note,recipient_user_id:'different-owner',is_read:true})});await h.handle.activate('client-updates');h.decorate();fire(h.root.querySelector('[data-client-notification-read]'),'click');await tick();assert.equal(note.is_read,false,'wrong recipient result must remain unconfirmed');});
import {clientRenewalPresentation} from '../assets/roles/client.js';
test('conflicting request/workflow cannot authorize an approved current stage',()=>{const view=clientRenewalPresentation({requestsState:{status:'ready',data:{requests:[{request_id:'same',loan_id:'loan',status:'rejected'}]}},workflowState:{status:'ready',data:{requests:[{request_id:'same',loan_id:'loan',status:'approved',client_decision:null}]}}});assert.equal(view.cards[0]?.workflow,null);assert.match(view.cards[0]?.nextStep||'',/unavailable|changed|refresh/i);});
const clientId='50000000-0000-4000-8000-000000000001',requestId='40000000-0000-4000-8000-000000000001';
test('Support uncertainty survives header and local reads without retry or erasing later text',async t=>{let posts=0;const h=await harness(t,{mutation:()=>{posts++;throw Object.assign(new Error('Response lost'),{code:'network_uncertain'});}});await h.handle.activate('client-support');h.decorate();const form=h.root.querySelector('#client-support-form');form.querySelector('[name="subject"]').value='Question';form.querySelector('[name="message"]').value='Unconfirmed question';fire(form,'submit');await tick();await h.handle.refreshVisible();await h.context.clientLoad('support',{refresh:true});form.querySelector('button[type="submit"]').disabled=false;fire(form,'submit');await tick();assert.equal(posts,1);assert.equal(form.querySelector('[name="message"]').value,'Unconfirmed question');assert.equal(h.context.clientMutations.state('support'),'uncertain');});
test('verified renewal with unchanged eligibility cannot repeat and keeps sibling Support draft',async t=>{let posts=0;const h=await harness(t,{mutation:(path,options)=>{posts++;return {request:{request_id:requestId,client_id:clientId,loan_id:'loan',status:'pending',submitted_at:'2026-10-02T01:00:00Z',requested_amount:'5000.00',client_message:options.body.message}};}});await h.handle.activate('client-renewals');h.decorate();const form=h.root.querySelector('#client-renewal-form');form.querySelector('[name="loanId"]').value='loan';form.querySelector('[name="requestedAmount"]').value='5000';form.querySelector('[name="message"]').value='Request';form.querySelector('button[type="submit"]').disabled=false;const sibling=h.root.querySelector('#client-support-form').querySelector('[name="message"]');sibling.value='Retain unrelated question';fire(form,'submit');await tick();await h.handle.refreshVisible();form.querySelector('button[type="submit"]').disabled=false;form.querySelector('[name="requestedAmount"]').value='5000';fire(form,'submit');await tick();assert.equal(posts,1);assert.equal(sibling.value,'Retain unrelated question');assert.equal(h.context.clientMutations.state('renewal:create:loan'),'saved');});
test('cash-confirm500 remains uncertain even when refreshed workflow offers the same action again',async t=>{const originalConfirm=globalThis.confirm;globalThis.confirm=()=>true;t.after(()=>globalThis.confirm=originalConfirm);let posts=0;const record={request_id:requestId,loan_id:'loan',status:'approved',cash_given_to_client_at:'2026-10-02T01:00:00Z',net_release_amount:'100.00'};const h=await harness(t,{renewals:{loans:[],requests:[record]},mutation:()=>{posts++;throw Object.assign(new Error('Server response unavailable'),{status:500});}});const original=h.context.api.request;h.context.api.request=async(path,options)=>path.endsWith('/renewal-workflow')?{requests:[record]}:original(path,options);await h.handle.activate('client-renewals');await tick();h.decorate();fire(h.root.querySelector('[data-client-renewal-cash-confirm]'),'click');await tick();await h.handle.refreshVisible();h.decorate();const repeated=h.root.querySelector('[data-client-renewal-cash-confirm]');assert.equal(repeated.disabled,true,JSON.stringify({posts,state:h.context.clientMutations.state('renewal:cash:'+requestId),markup:repeated.outerHTML}));repeated.disabled=false;fire(repeated,'click');await tick();assert.equal(posts,1);assert.equal(h.context.clientMutations.state('renewal:cash:'+requestId),'uncertain');});
test('cash response with changed locked cash is unconfirmed even if its timestamp is present',async()=>{await assert.rejects(requestClientRenewalCashConfirmation({api:{request:async()=>({request:{request_id:requestId,net_release_amount:'99.00',client_cash_confirmed_at:'2026-10-02T01:00:00Z'}})},requestId,expectedRecord:{net_release_amount:'100.00'},confirmAction:()=>true}),error=>error.code==='client_result_unverified');});
import {requestClientRenewalDecision,requestClientRenewalSignature,requestClientRenewalCancellation,verifyClientCreatedRequest} from '../assets/roles/client.js';
test('each continuation verifies its exact target and resulting action fact',async()=>{for(const [helper,options,bad,good] of [[requestClientRenewalCancellation,{requestId},{request_id:requestId,status:'pending'},{request_id:requestId,status:'cancelled'}],[requestClientRenewalDecision,{requestId,decision:'accepted'},{request_id:requestId,client_decision:'declined'},{request_id:requestId,client_decision:'accepted'}],[requestClientRenewalSignature,{requestId,signerId:'own'},{request_id:requestId,signers:[{signer_id:'other',signed:true}]},{request_id:requestId,signers:[{signer_id:'own',signed:true}]}]]){await assert.rejects(helper({...options,api:{request:async()=>({request:bad})},confirmAction:()=>true,confirmCancel:()=>true}),error=>error.code==='client_result_unverified');assert.equal(await helper({...options,api:{request:async()=>({request:good})},confirmAction:()=>true,confirmCancel:()=>true}),true);await assert.rejects(helper({...options,api:{request:async()=>({request:{...good,request_id:'another'}})},confirmAction:()=>true,confirmCancel:()=>true}),error=>error.code==='client_result_unverified');}});
test('created request validation uses server normalized text and exact identity/amount rather than truthiness',()=>{const body={loan_id:'own-loan',requested_amount:'5,000.00',message:'  Request   text '};const result={request:{request_id:requestId,client_id:clientId,loan_id:'own-loan',requested_amount:'5000.00',client_message:'Request text',status:'pending',submitted_at:'2026-10-02T01:00:00Z'}};assert.equal(verifyClientCreatedRequest(result,{kind:'renewal',body,clientId}).request_id,requestId);for(const request of [{...result.request,client_id:'60000000-0000-4000-8000-000000000001'},{...result.request,loan_id:'other-loan'},{...result.request,requested_amount:'4999.99'},{...result.request,status:'approved'}])assert.throws(()=>verifyClientCreatedRequest({request},{kind:'renewal',body,clientId}),error=>error.code==='client_result_unverified');});

test('a rejected renewal response after authority change cannot toast or restore stale controls',async t=>{
 const previousDocument=globalThis.document,previousConfirm=globalThis.confirm;const toasts=[];
 globalThis.document={getElementById:()=>({append:toast=>toasts.push(toast.textContent)}),createElement:()=>({remove(){}})};globalThis.confirm=()=>true;
 t.after(()=>{globalThis.document=previousDocument;globalThis.confirm=previousConfirm;});let reject;
 const record={request_id:requestId,loan_id:'loan',status:'approved',client_decision:null};
 const h=await harness(t,{renewals:{loans:[],requests:[record]},mutation:()=>new Promise((resolve,rejectRequest)=>reject=rejectRequest)});
 const original=h.context.api.request;h.context.api.request=async(path,options)=>path.endsWith('/renewal-workflow')?{requests:[record]}:original(path,options);
 await h.handle.activate('client-renewals');await tick();h.decorate();fire(h.root.querySelector('[data-client-renewal-decision="accepted"]'),'click');await tick();
 h.context.session.user.id='another-owner';reject(Object.assign(new Error('Private old request failed'),{status:500}));await tick();
 assert.equal(h.root.innerHTML,'');assert.deepEqual(toasts,[]);
});

test('created request identity is compared with the submitted borrower snapshot',async t=>{
 let resolve;const h=await harness(t,{mutation:()=>new Promise(done=>resolve=done)});await h.handle.activate('client-support');h.decorate();h.context.clientRaw.support.client={client_id:clientId};
 const form=h.root.querySelector('#client-support-form');form.querySelector('[name="category"]').value='other';form.querySelector('[name="subject"]').value='Question';form.querySelector('[name="message"]').value='Keep this borrower question';fire(form,'submit');await tick();
 const differentClient='60000000-0000-4000-8000-000000000001';h.context.clientRaw.support.client={client_id:differentClient};resolve({request:{request_id:requestId,client_id:differentClient,category:'other',subject:'Question',message:'Keep this borrower question',reference_text:'',status:'open',created_at:'2026-10-02T01:00:00Z'}});await tick();
 assert.equal(form.querySelector('[name="message"]').value,'Keep this borrower question');assert.equal(h.context.clientMutations.state('support'),'uncertain');
});
