import test from 'node:test';import assert from 'node:assert/strict';import {createTreasuryClient} from '../assets/treasury-api.js';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const actor={user_id:id(1),device_id:id(2)},account=id(3),context=id(4),creditId=id(5);
export const session={user:{id:actor.user_id,role:'collector',status:'active'},device_id:'installation',device_registered:true,permissions:[]};
export const credit={id:creditId,version:1,case_id:null,opening_anchor_id:null,origin_account_id:account,ledger_context_id:context,collector_user_id:actor.user_id,recognized_amount:'100.00',reclassified_amount:'0.00',returned_amount:'0.00',applied_amount:'0.00',outstanding_amount:'100.00',reserved_amount:'0.00',available_amount:'100.00',frozen:false,status:'outstanding',created_at:'2026-10-02T08:00:00+08:00',entries:[]};
export const projection={collector_surplus_contract_version:1,actor,mode:'own',readiness:{enabled:true,treasury_ready:true,application_enabled:false,application_supported:false,historical_correction_supported:false,gl_supported:false,blockers:[]},capabilities:{view:true,return_request:true},accounts:[],collector_choices:[],kind:'credits',items:[credit],total_count:1,totals:{recognized_amount:'100.00',outstanding_amount:'100.00',reserved_amount:'0.00',available_amount:'100.00',returned_amount:'0.00',applied_amount:'0.00',reclassified_amount:'0.00'},has_more:false,limit:50,offset:0};
const command={action:'collector_surplus_return_request',request_id:id(6),credit_id:creditId,credit_version:1,amount:'40.00',destination:{kind:'physical_cash',recipient_reference:null},reason:'Synthetic return request'};
const request={id:id(7),version:1,kind:'return',credit_id:creditId,collector_user_id:actor.user_id,amount:'40.00',destination:command.destination,remittance_id:null,source_digest:null,status:'requested',created_at:credit.created_at};
const outcome={contract_version:1,request_id:command.request_id,action:command.action,status:'saved',target_id:request.id,version:1,result:{collector_surplus_contract_version:1,disposition:'requested',actor_user_id:actor.user_id,device_id:actor.device_id,account_id:account,ledger_context_id:context,source_account_id:account,blockers:[],count:null,settlement:null,case:null,credit:null,request,action_record:null,acknowledgment:null,exception:null,opening_anchor:null}};
function make(response=outcome){let current=session;const calls=[];const client=createTreasuryClient({request:async(path,options={})=>{calls.push({path,options});if(path.includes('/collector-surplus/workspace'))return projection;if(path.includes('/credits/'))return credit;return response;}},{getSession:()=>current});return {client,calls,revoke:()=>current=null};}
test('own Collector requests use frozen strict command without granting wallet access',async()=>{const h=make();assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();const result=await h.client.execute(command);assert.equal(result.result.disposition,'requested');const post=h.calls.find(x=>x.options.financial);assert.deepEqual(post.options.body,command);assert.equal('account_id' in post.options.body,false);assert.equal(h.calls.some(x=>/accounts|events|\/workspace$/.test(x.path)),false);h.client.dispose();});
test('malformed money, extra authority and another Collector filter fail before writes',async()=>{const h=make();assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();for(const body of [{...command,amount:40},{...command,amount:'40.001'},{...command,account_id:account},{...command,amount:'0.00'}])await assert.rejects(h.client.execute(body));await assert.rejects(h.client.surplusWorkspace({collectorUserId:id(99)}));assert.equal(h.calls.some(x=>x.options.financial),false);h.client.dispose();});
test('lost response locks same request and null/wrong recovered result cannot unlock',async()=>{let recovery=null,posts=0;const client=createTreasuryClient({request:async(path,options={})=>{if(path.includes('/collector-surplus/workspace'))return projection;if(path.includes('/requests/'))return recovery;if(options.financial){posts++;throw Object.assign(Error('lost'),{code:'network_uncertain'});}}},{getSession:()=>session});assert.equal(typeof client.surplusWorkspace,'function');await client.surplusWorkspace();await assert.rejects(client.execute(command));assert.equal(client.state().status,'uncertain');assert.equal(await client.recover(),null);await assert.rejects(client.execute({...command,request_id:id(8)}));recovery={...outcome,request_id:id(9)};await assert.rejects(client.recover());assert.equal(client.state().status,'uncertain');recovery=outcome;assert.equal((await client.recover()).result.disposition,'requested');assert.equal(client.state().status,'idle');assert.equal(posts,1);client.dispose();});
test('paid or wrong-account result cannot masquerade as own request',async()=>{for(const response of [{...outcome,result:{...outcome.result,disposition:'paid'}},{...outcome,result:{...outcome.result,account_id:id(99)}}]){const h=make(response);assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();await assert.rejects(h.client.execute(command));assert.equal(h.client.state().status,'uncertain');h.client.dispose();}});
test('scope change disposes private surplus data before subsequent reads',async()=>{const h=make();assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();h.revoke();await assert.rejects(h.client.surplusWorkspace());assert.equal(h.client.state().status,'disposed');});
