import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {Element,fire} from './helpers/dom.mjs';import {mountCollectorSurplus} from '../assets/collector-surplus.js';
const {examples}=JSON.parse(await readFile(new URL('./fixtures/collector-surplus-backend.json',import.meta.url),'utf8'));
const get=kind=>examples.find(e=>e.kind===kind),workspace=get('staff-workspace-credits').response.data,actor=workspace.actor,account=workspace.accounts[0];
const settle=async()=>{for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));};
for(const loseCountResponse of [false,true])test((loseCountResponse?'recovered':'verified')+' count → accept → recognition reload current account version and retain unrelated drafts and File',async()=>{
 const root=new Element(),session={user:{id:actor.user_id,role:'management',status:'active'},device_id:'synthetic',device_registered:true,permissions:[]},rows=new Map(),posts=[];let version=1,state='idle',reads=0,recovery=null;
 const preview=get('preview').response.data;rows.set(preview.remittance_id,{...preview,id:preview.remittance_id,total_amount:preview.gross_obligation});
 const kinds={count:'counts',case:'cases',credit:'credits'};
 const client={isCurrent:()=>true,state:()=>({status:state}),workspace:async()=>{},surplusWorkspace:async({kind,accountId,offset=0})=>{reads++;return {...workspace,kind,accounts:(accountId?[account]:workspace.accounts).map(a=>({...a,version})),items:[...rows.values()].filter(r=>r._kind===kind||kind==='remittances'&&r.remittance_id===preview.remittance_id&&!r.counted_amount),totals:{},total_count:0,offset};},surplusPreview:async()=>({...preview,account_version:version}),surplusDetail:async(_kind,id)=>rows.get(id),uploadEvidence:async()=>({result:{evidence:{id:get('collector_count_record').command.evidence_id,account_id:account.id,purpose:'recipient'}}}),execute:async body=>{assert.equal(body.expected_version,version,'next phase must use current server account version');posts.push(body);version++;const result=structuredClone(get(body.action).response.data);result.request_id=body.request_id;for(const [slot,kind] of Object.entries(kinds)){const row=result.result[slot];if(row)rows.set(row.id,{...row,_kind:kind});}if(loseCountResponse&&body.action==='collector_count_record'){state='uncertain';recovery=result;throw Error('Synthetic lost response');}return result;},recover:async()=>{state='idle';return recovery;}};
 const handle=mountCollectorSurplus({root,getSession:()=>session,client,mode:'staff',confirmAction:()=>true});await handle.ready;
 const unrelated=root.querySelector('[data-surplus-form="collector_surplus_opening_prepare"]'),reason=unrelated.querySelector('[name="reason"]');reason.value='Retained separate draft';const file=root.querySelector('[data-surplus-file]'),selected=new Blob(['synthetic only'],{type:'image/png'});file.files=[selected];fire(file,'change');fire(root.querySelector('[data-surplus-upload]'),'submit');await settle();
 async function phase(action){const e=get(action),form=root.querySelector(`[data-surplus-form="${action}"]`);fire(root.querySelector(`[data-surplus-navigation="${action==='collector_count_record'?'remittances':action==='collector_count_accept'?'counts':'cases'}"]`),'click');await settle();for(const node of form.querySelectorAll('[data-surplus-field]')){const key=node.getAttribute('name');if(e.command[key]!==undefined){if(node.getAttribute('type')==='checkbox')node.checked=e.command[key];else node.value=key.endsWith('_at')?e.command[key].slice(0,19):e.command[key];}}if(action==='collector_count_record'){fire(form.querySelector('[data-surplus-preview]'),'click');await settle();}fire(form,'submit');await settle();if(state==='uncertain'){const before=reads;assert.equal(await handle.refreshReadOnly(),false);assert.equal(reads,before);assert.equal(file.files[0],selected);fire(root.querySelector('[data-surplus-recover]'),'click');await settle();assert.equal(state,'idle');assert.ok(reads>before);}assert.doesNotMatch(root.querySelector('[data-surplus-status]').textContent,/current account version|incomplete|another account/);}
 await phase('collector_count_record');await phase('collector_count_accept');await phase('collector_surplus_recognize');
 assert.deepEqual(posts.map(b=>b.expected_version),[1,2,3]);assert.ok(reads>=8);assert.equal(reason.value,'Retained separate draft');assert.equal(root.querySelector('[data-surplus-file]'),file);assert.equal(file.files[0],selected);handle();
});

test('cross-account return request remains origin-bound while reserve uses deliberately chosen paying account',async()=>{
 const root=new Element(),session={user:{id:actor.user_id,role:'management',status:'active'},device_id:'synthetic',device_registered:true,permissions:[]},request=get('collector_surplus_return_request').response.data.result.request,credit=get('collector_surplus_recognize').response.data.result.credit,paying=workspace.accounts[1],calls=[],posts=[];
 const client={isCurrent:()=>true,state:()=>({status:'idle'}),surplusWorkspace:async f=>{calls.push(f);return {...workspace,kind:f.kind,accounts:f.accountId?workspace.accounts.filter(a=>a.id===f.accountId):workspace.accounts,items:f.kind==='requests'&&!f.accountId?[request]:[],totals:{},total_count:f.kind==='requests'&&!f.accountId?1:0,offset:0};},surplusDetail:async(k)=>k==='requests'?request:credit,workspace:async()=>{},uploadEvidence:async()=>({result:{evidence:{id:get('collector_surplus_return_prepare').command.evidence_id,account_id:paying.id,purpose:'recipient'}}}),execute:async body=>{posts.push(body);return {...get('collector_surplus_return_prepare').response.data,request_id:body.request_id};}};
 const handle=mountCollectorSurplus({root,client,getSession:()=>session,mode:'staff',confirmAction:()=>true});await handle.ready;const accountSelect=root.querySelector('[data-surplus-account]');accountSelect.value=paying.id;fire(accountSelect,'change');await settle();fire(root.querySelector('[data-surplus-navigation="requests"]'),'click');await settle();const form=root.querySelector('[data-surplus-form="collector_surplus_return_prepare"]');fire(form.querySelector('[data-surplus-source-requests]'),'click');await settle();assert.equal(accountSelect.value,paying.id);assert.equal(calls.at(-1).accountId,paying.id);form.querySelector('[name="collector_request_id"]').value=request.id;fire(form.querySelector('[name="collector_request_id"]'),'change');const file=root.querySelector('[data-surplus-file]');file.files=[new Blob(['synthetic'],{type:'image/png'})];fire(file,'change');fire(root.querySelector('[data-surplus-upload]'),'submit');await settle();form.querySelector('[name="evidence_id"]').value=get('collector_surplus_return_prepare').command.evidence_id;form.querySelector('[name="reason"]').value='Evidenced cross-account return approval';fire(form,'submit');await settle();assert.equal(posts.length,1);assert.equal(posts[0].account_id,paying.id);assert.equal(posts[0].credit_id,credit.id);assert.equal(posts[0].amount,request.amount);assert.deepEqual(posts[0].destination,request.destination);handle();
});
