import test from 'node:test';import assert from 'node:assert/strict';import {Element,fire} from './helpers/dom.mjs';
const module=await import('../assets/collector-surplus.js').catch(()=>({}));
const id=n=>`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor={user_id:id(1),device_id:id(2)},session={user:{id:actor.user_id,role:'management',status:'active'},device_id:'install',device_registered:true,permissions:['treasury.collector_surplus.view']};
const base={collector_surplus_contract_version:1,actor,mode:'staff',readiness:{enabled:true,treasury_ready:true,application_enabled:false,application_supported:false,historical_correction_supported:false,gl_supported:false,blockers:[{code:'historical',message:'Historical correction adapter unavailable.'}]},capabilities:{view:true,count_record:true,count_accept:true,recognize:true,return_prepare:true,return_record:true,opening_prepare:true,opening_activate:true,exception_record:true},accounts:[{id:id(3),ledger_context_id:id(4),version:1,kind:'physical_cash',alias:'Synthetic counted cash',custodian_user_id:actor.user_id,actions:['count_record','count_accept','recognize','return_prepare','return_record','opening_prepare','opening_activate','exception_record']}],collector_choices:[{user_id:id(5),name:'Synthetic Collector'}],kind:'credits',items:[],total_count:0,totals:{outstanding_amount:'90071992547409.93'},has_more:false,limit:50,offset:0};
async function mount(t,{own=false}={}){assert.equal(typeof module.mountCollectorSurplus,'function');let live=session;const root=new Element(),calls=[],controller=new AbortController(),projection=own?{...base,mode:'own',accounts:[],collector_choices:[],capabilities:{view:true,return_request:true,return_acknowledge:true,application_request:true}}:base;const handle=module.mountCollectorSurplus({root,mode:own?'own':undefined,getSession:()=>live,signal:controller.signal,api:{request:async(p,o={})=>{calls.push({p,o});if(p.includes('/collector-surplus/workspace')){const q=new URLSearchParams(p.split('?')[1]);return {...projection,kind:q.get('kind'),offset:Number(q.get('offset')),limit:Number(q.get('limit'))};}if(p==='/api/v1/treasury/workspace')return {contract_version:1,actor,enabled:true,owner_configured:true,capabilities:{evidence_upload:true},accounts:[{...base.accounts[0],balance:null,actions:['evidence_upload','receipt_verify']}],claims:[],blockers:[]};return {items:[],total_count:0,totals:null,limit:50,offset:0,has_more:false};}}});t.after(handle);await handle.ready;return {root,handle,calls,revoke:()=>live=null,controller};}
test('staff count/credit/return/opening/exception forms exist and blocked adapters are explicit',async t=>{const h=await mount(t);for(const action of ['collector_count_record','collector_count_accept','collector_surplus_recognize','collector_surplus_return_prepare','collector_surplus_return_record','collector_surplus_opening_prepare','collector_surplus_opening_activate','collector_custody_exception_record'])assert.ok(h.root.querySelector(`[data-surplus-form="${action}"]`),action);assert.match(h.root.textContent,/Historical correction adapter unavailable/);assert.doesNotMatch(h.root.textContent,/Application completed|Journal posted/);});
test('own credit shows server totals with no office approval/editor/history requests',async t=>{const h=await mount(t,{own:true});assert.match(h.root.textContent,/90,071,992,547,409.93/);assert.ok(h.root.querySelector('[data-surplus-form="collector_surplus_return_request"]'));assert.equal(h.root.querySelector('[data-surplus-form="collector_surplus_recognize"]'),null);assert.equal(h.calls.some(x=>/\/accounts\/|\/events|\/treasury\/workspace$/.test(x.p)),false);});
test('refresh retains draft text and exact selected File nodes',async t=>{const h=await mount(t),form=h.root.querySelector('[data-surplus-form="collector_surplus_recognize"]'),node=form.querySelector('[name="amount"]'),file=h.root.querySelector('[data-surplus-file]');node.value='40.00';const selected=new Blob(['synthetic'],{type:'image/png'});file.files=[selected];await h.handle.refreshReadOnly();assert.equal(h.root.querySelector('[data-surplus-form="collector_surplus_recognize"]'),form);assert.equal(node.value,'40.00');assert.equal(h.root.querySelector('[data-surplus-file]'),file);assert.equal(file.files[0],selected);assert.equal(h.calls.some(x=>x.o.financial),false);});
test('scope change and abort remove all private draft and File state',async t=>{const h=await mount(t);h.revoke();await h.handle.refreshReadOnly();assert.equal(h.root.innerHTML,'');const second=await mount(t);second.controller.abort();assert.equal(second.root.innerHTML,'');});
test('private task opens under sharing stop and leaves safe server money unchanged',async()=>{assert.equal(typeof module.renderSurplusPage,'function');const html=module.renderSurplusPage({...base,total_count:200,items:[]});assert.match(html,/200/);assert.match(html,/90,071,992,547,409.93/);assert.match(html,/Server totals/);});
