import test from 'node:test';
import assert from 'node:assert/strict';
import {Element,fire} from './helpers/dom.mjs';
import {renderCollectorRenewals,mountCollectorRenewals} from '../assets/collector-renewals.js';
import {createCollectorWriteGuard} from '../assets/collector-write-guard.js';
const session={permissions:['renewal.cash_custody.assigned']};
const item={request_id:'r',loan_id:'l',client_name:'Borrower',status:'approved',requested_amount:'12000.00',approved_principal:'10000.00',renewal_offset_amount:'1500.00',net_release_amount:'8500.00',collector_cash_received_at:'now',cash_given_to_client_at:'now',handover_proof_status:'not_submitted',review_note:'Office note'};
test('all returned cash context zero offset lock and management note show without inferred cash',()=>{const html=renderCollectorRenewals([item],session);for(const text of ['Requested amount','12,000.00','Approved principal','10,000.00','Renewal offset','1,500.00','Net cash to client','8,500.00','not locked','Office note','Not submitted'])assert.ok(html.includes(text),text);assert.match(renderCollectorRenewals([{...item,renewal_offset_amount:'0.00',amount_locked_at:'now'}],session),/₱0\.00/);assert.match(renderCollectorRenewals([{...item,net_release_amount:'NaN'}],session),/Unavailable/);});
test('borrower decline reason and actual cash stages remain visible separately from approval',()=>{
  const html=renderCollectorRenewals([{...item,client_decision:'declined',collector_reason_code:'Payment capacity concern',cash_released_to_collector_at:'2026-10-01T10:00:00Z',collector_cash_received_at:'2026-10-01T10:10:00Z',cash_given_to_client_at:null}],session);
  for(const text of ['Borrower decision: Declined','Payment capacity concern','Cash released to Collector','2026-10-01T10:00:00Z','Collector cash received','2026-10-01T10:10:00Z','Cash given to client','Borrower declined'])assert.ok(html.includes(text),text);
  assert.doesNotMatch(html,/Waiting for the next authorized/);assert.doesNotMatch(html,/<form/);
});
test('local refresh retains unrelated photo node and exact request opening makes no write',async()=>{const root=new Element(),guard=createCollectorWriteGuard({eventTarget:new EventTarget(),onLock(){}});let handle;let calls=0;const cleanup=mountCollectorRenewals({root,guard,session,getSession:()=>session,registerHandle:value=>handle=value,onSaved:async()=>{},api:{request:async()=>{calls++;return {requests:[item,{...item,request_id:'second'}]};}}});await handle.refresh();const photo=root.querySelector('[data-renewal-id="second"]').querySelector('[name="photo"]');photo.files=[{name:'draft.jpg',type:'image/jpeg',size:1}];await handle.refresh();assert.strictEqual(root.querySelector('[data-renewal-id="second"]').querySelector('[name="photo"]'),photo);const before=calls;assert.equal(await handle.openRequest('r'),true);assert.equal(calls,before);cleanup();assert.equal(handle,null);guard.dispose();});
