import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {validateSurplusWorkspace} from '../assets/collector-surplus-contract.js';import {createTreasuryClient} from '../assets/treasury-api.js';
const {examples}=JSON.parse(await readFile(new URL('./fixtures/collector-surplus-backend.json',import.meta.url),'utf8')),page=examples.find(e=>e.kind==='own-workspace-credits').response.data;
const validate=p=>validateSurplusWorkspace(p,{actorId:p.actor.user_id,kind:p.kind,limit:p.limit,offset:p.offset});
for(const field of ['reason','recipient_attestation','cancellation_evidence_id','unknown_private_field'])test(`own row rejects staff-only ${field}`,()=>{assert.equal(validate(page),page);const p=structuredClone(page);p.items[0][field]='Private staff content';assert.throws(()=>validate(p));});
for(const field of ['entries','resolutions','acknowledgment','destination'])test(`own ${field} cannot smuggle private staff content`,()=>{const p=structuredClone(page);if(['entries','resolutions'].includes(field))p.items[0][field]=[{id:crypto.randomUUID(),kind:'synthetic',amount:'1.00',created_at:'2026-10-02T10:00:00Z',reason:'private'}];else p.items[0][field]={reason:'private'};assert.throws(()=>validate(p));});
test('own private export rejects extra outer keys and staff fields before returning bytes',async()=>{let envelope={success:true,data:{...page,has_more:false}};const session={user:{id:page.actor.user_id,role:'collector',status:'active'},device_registered:true,device_id:'synthetic'},client=createTreasuryClient({request:async(p)=>p.includes('/export?')?new Blob([JSON.stringify(envelope)],{type:'application/json'}):page},{getSession:()=>session});try{assert.ok(await client.surplusExport({mode:'own'}));envelope={...envelope,private_staff:'private'};await assert.rejects(client.surplusExport({mode:'own'}));envelope={success:true,data:structuredClone(page)};envelope.data.items[0].reason='private';await assert.rejects(client.surplusExport({mode:'own'}));}finally{client.dispose();}});

test('allowed scalar fields cannot carry nested private payloads',()=>{for(const target of ['created_at','entry','destination']){const p=structuredClone(page);if(target==='entry')p.items[0].entries=[{id:crypto.randomUUID(),kind:'synthetic',amount:'1.00',created_at:{reason:'private'}}];else if(target==='destination')p.items[0].destination={kind:'physical_cash',recipient_reference:{reason:'private'}};else p.items[0].created_at={reason:'private'};assert.throws(()=>validate(p));}});

for(const field of ['actor','readiness','blocker'])test(`own ${field} metadata excludes private staff payloads from export`,async()=>{const p=structuredClone(page);if(field==='actor')p.actor.private_identifier='private';else if(field==='readiness')p.readiness.private_identifier='private';else p.readiness.blockers.push({code:'synthetic',message:'Safe explanation',evidence_id:crypto.randomUUID()});assert.throws(()=>validate(p));const session={user:{id:p.actor.user_id,role:'collector',status:'active'},device_registered:true,device_id:'synthetic'},client=createTreasuryClient({request:async(path)=>path.includes('/export?')?new Blob([JSON.stringify({success:true,data:p})],{type:'application/json'}):page},{getSession:()=>session});try{await assert.rejects(client.surplusExport({mode:'own'}));}finally{client.dispose();}});
