import test from 'node:test';import assert from 'node:assert/strict';import {createTreasuryClient} from '../assets/treasury-api.js';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const actor={user_id:id(1),device_id:id(2)},account=id(3),context=id(4),creditId=id(5);
export const session={user:{id:actor.user_id,role:'collector',status:'active'},device_id:'installation',device_registered:true,permissions:[]};
export const credit={id:creditId,version:1,case_id:null,opening_anchor_id:null,origin_account_id:account,ledger_context_id:context,collector_user_id:actor.user_id,recognized_amount:'100.00',reclassified_amount:'0.00',returned_amount:'0.00',applied_amount:'0.00',outstanding_amount:'100.00',reserved_amount:'0.00',available_amount:'100.00',frozen:false,status:'outstanding',created_at:'2026-10-02T08:00:00+08:00',entries:[]};
export const projection={collector_surplus_contract_version:1,actor,mode:'own',readiness:{enabled:true,treasury_ready:true,application_enabled:false,application_supported:false,historical_correction_supported:false,gl_supported:false,blockers:[]},capabilities:{view:true,return_request:true},accounts:[],collector_choices:[],kind:'credits',items:[credit],total_count:1,totals:{recognized_amount:'100.00',outstanding_amount:'100.00',reserved_amount:'0.00',available_amount:'100.00',returned_amount:'0.00',applied_amount:'0.00',reclassified_amount:'0.00'},has_more:false,limit:50,offset:0};
const command={action:'collector_surplus_return_request',request_id:id(6),credit_id:creditId,credit_version:1,amount:'40.00',destination:{kind:'physical_cash',recipient_reference:null},reason:'Synthetic return request'};
const request={id:id(7),version:1,kind:'return',credit_id:creditId,collector_user_id:actor.user_id,amount:'40.00',destination:command.destination,remittance_id:null,source_digest:null,status:'requested',created_at:credit.created_at};
const outcome={contract_version:1,request_id:command.request_id,action:command.action,status:'saved',target_id:request.id,version:1,result:{collector_surplus_contract_version:1,disposition:'requested',actor_user_id:actor.user_id,device_id:actor.device_id,account_id:account,ledger_context_id:context,source_account_id:account,blockers:[],count:null,settlement:null,case:null,credit:null,request,action_record:null,acknowledgment:null,exception:null,opening_anchor:null}};
function make(response=outcome){let current=session;const calls=[];const client=createTreasuryClient({request:async(path,options={})=>{calls.push({path,options});if(path.includes('/collector-surplus/workspace'))return projection;if(path.includes('/credits/'))return credit;return response;}},{getSession:()=>current});return {client,calls,revoke:()=>current=null};}
test('own Collector requests use frozen strict command without granting wallet access',async()=>{const h=make();assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();const result=await h.client.execute(command);assert.equal(result.result.disposition,'requested');const post=h.calls.find(x=>x.options.financial);assert.deepEqual(post.options.body,command);assert.equal('account_id' in post.options.body,false);assert.equal(h.calls.some(x=>/accounts|events|\/workspace$/.test(x.path)),false);h.client.dispose();});
test('malformed money, extra authority and another Collector filter fail before writes',async()=>{const h=make();assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();for(const body of [{...command,amount:40},{...command,amount:'40.001'},{...command,account_id:account},{...command,amount:'0.00'}])await assert.rejects(h.client.execute(body));await assert.rejects(h.client.surplusWorkspace({collectorUserId:id(99)}));assert.equal(h.calls.some(x=>x.options.financial),false);h.client.dispose();});
test('lost response locks same request and null/wrong recovered result cannot unlock',async()=>{let recovery=null,posts=0;const client=createTreasuryClient({request:async(path,options={})=>{if(path.includes('/collector-surplus/workspace'))return projection;if(path.includes('/requests/'))return recovery;if(options.financial){posts++;throw Object.assign(Error('lost'),{code:'network_uncertain'});}}},{getSession:()=>session});assert.equal(typeof client.surplusWorkspace,'function');await client.surplusWorkspace();await assert.rejects(client.execute(command));assert.equal(client.state().status,'uncertain');assert.equal(await client.recover(),null);await assert.rejects(client.execute({...command,request_id:id(8)}));recovery={...outcome,request_id:id(9)};await assert.rejects(client.recover());assert.equal(client.state().status,'uncertain');recovery=outcome;assert.equal((await client.recover()).result.disposition,'requested');assert.equal(client.state().status,'idle');assert.equal(posts,1);client.dispose();});
test('paid or wrong-account result cannot masquerade as own request',async()=>{for(const response of [{...outcome,result:{...outcome.result,disposition:'paid'}},{...outcome,result:{...outcome.result,account_id:id(99)}}]){const h=make(response);assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();await assert.rejects(h.client.execute(command));assert.equal(h.client.state().status,'uncertain');h.client.dispose();}});
test('scope change disposes private surplus data before subsequent reads',async()=>{const h=make();assert.equal(typeof h.client.surplusWorkspace,'function');await h.client.surplusWorkspace();h.revoke();await assert.rejects(h.client.surplusWorkspace());assert.equal(h.client.state().status,'disposed');});

const contract=await import('../assets/collector-surplus-contract.js');
test('all strict new command shapes match the frozen machine-readable contract',async()=>{const {readFile}=await import('node:fs/promises'),frozen=JSON.parse(await readFile(new URL('../../docs/operations/collector-surplus-command-schema.json',import.meta.url),'utf8'));function clean(v){if(Array.isArray(v))return v.map(clean);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).filter(([k])=>!['title','default'].includes(k)).map(([k,x])=>[k,clean(x)]));return v;}assert.deepEqual(Object.values(contract.surplusActions).sort(),Object.entries(frozen.$defs).filter(([,d])=>d.properties?.action?.const?.startsWith('collector_')).map(([k])=>k).sort());for(const name of Object.values(contract.surplusActions))assert.deepEqual(contract.surplusSchemas[name],clean(frozen.$defs[name]),name);});
test('count result must preserve reviewed required cash and original source snapshot amounts',()=>{const body={action:'collector_count_record',request_id:id(10),account_id:account,expected_version:1,remittance_id:id(11),source_digest:'a'.repeat(64),counted_amount:'10100.00',counted_at:credit.created_at,evidence_id:id(12),recipient_attestation:'Synthetic count',review_acknowledged:true},reference={remittance_id:body.remittance_id,physical_cash_required:'10000.00',gross_obligation:'10000.00',refund_due_total:'0.00'},row={id:id(13),version:1,remittance_id:body.remittance_id,account_id:account,ledger_context_id:context,collector_user_id:id(14),recipient_user_id:actor.user_id,source_digest:body.source_digest,gross_obligation:'9999.00',refund_due_total:'0.00',physical_cash_required:'9999.00',counted_amount:body.counted_amount,difference:'101.00',disposition:'counted_ready',counted_at:credit.created_at,recorded_at:credit.created_at};const result={...outcome,request_id:body.request_id,action:body.action,target_id:row.id,result:{...outcome.result,disposition:'counted_ready',count:row,request:null}},held={options:{body},actor,accountId:account,contextId:context,collectorId:row.collector_user_id,reference};assert.throws(()=>contract.validateSurplusResult(result,held));});
test('normal count accepts zero observation and rejects false review and float money',()=>{const body={action:'collector_count_record',request_id:id(10),account_id:account,expected_version:1,remittance_id:id(11),source_digest:'a'.repeat(64),counted_amount:'0.00',counted_at:credit.created_at,evidence_id:id(12),recipient_attestation:'Synthetic count',review_acknowledged:true};assert.equal(contract.validateSurplusCommand(body),body);assert.throws(()=>contract.validateSurplusCommand({...body,review_acknowledged:false}));assert.throws(()=>contract.validateSurplusCommand({...body,counted_amount:0}));});

test('zero physical exact settlement accepts null event but positive cash requires event',()=>{const body={action:'collector_count_accept',request_id:id(20),account_id:account,expected_version:2,count_id:id(21),count_version:1,source_digest:'a'.repeat(64),physical_receipt_acknowledged:true},reference={id:body.count_id,remittance_id:id(22),counted_amount:'0.00',gross_obligation:'0.00',difference:'0.00'},collector=id(23),row={id:id(24),version:1,remittance_id:reference.remittance_id,count_id:body.count_id,collector_user_id:collector,recipient_user_id:actor.user_id,account_id:account,ledger_context_id:context,event_id:null,physical_amount:'0.00',authorized_credit_amount:'0.00',gross_obligation:'0.00',accepted_at:credit.created_at},result={...outcome,action:body.action,request_id:body.request_id,target_id:row.id,result:{...outcome.result,disposition:'accepted_exact',request:null,settlement:row}},held={options:{body},actor,accountId:account,contextId:context,collectorId:collector,reference};assert.equal(contract.validateSurplusResult(result,held),result);assert.throws(()=>contract.validateSurplusResult({...result,result:{...result.result,settlement:{...row,physical_amount:'100.00'}}},{...held,reference:{...reference,counted_amount:'100.00'}}));});
test('recognition binds exact principal and rejects malformed cached nested case',()=>{const body={action:'collector_surplus_recognize',request_id:id(20),account_id:account,expected_version:2,case_id:id(21),case_version:1,amount:'40.00',source_digest:'a'.repeat(64),evidence_id:id(22),reason:'Independent ownership review',source_review_acknowledged:true},collector=id(23),row={...credit,id:id(24),collector_user_id:collector,case_id:body.case_id,recognized_amount:'40.00',outstanding_amount:'40.00',available_amount:'40.00'},held={options:{body},actor,accountId:account,contextId:context,collectorId:collector,reference:{id:body.case_id}},result={...outcome,action:body.action,request_id:body.request_id,target_id:row.id,result:{...outcome.result,request:null,disposition:'recognized',credit:row}};assert.throws(()=>contract.validateSurplusResult({...result,result:{...result.result,credit:{...row,recognized_amount:'100.00'}}},held));assert.throws(()=>contract.validateSurplusResult({...result,result:{...result.result,case:{id:body.case_id,version:2,account_id:account,ledger_context_id:context,collector_user_id:collector,status:'resolved',received_excess_amount:'oops',unidentified_amount:'0.00'}}},held));assert.equal(contract.validateSurplusResult(result,held),result);});

test('own detail and export propagate explicit own mode even when actor also has staff grants',async()=>{const calls=[],client=createTreasuryClient({request:async(p)=>{calls.push(p);if(p.includes('/workspace'))return projection;const q=new URLSearchParams(p.split('?')[1]);if(p.includes('/credits/'))return q.get('mode')==='own'?credit:{...credit,evidence_id:id(99)};return new Blob([JSON.stringify({success:true,data:{...projection,limit:50,offset:0}})],{type:'application/json'});}},{getSession:()=>session});await client.surplusWorkspace({mode:'own'});assert.equal((await client.surplusDetail('credits',creditId)).id,creditId);await client.surplusExport();assert.ok(calls.filter(p=>!p.includes('/workspace')).every(p=>new URLSearchParams(p.split('?')[1]).get('mode')==='own'));client.dispose();});

test('own private report rejects office metadata outside its safe projection',()=>{for(const change of [{balance:{expected_balance:'10000.00'}},{opening_choices:[{id:id(99),amount:'10000.00'}]},{totals:{...projection.totals,actual_wallet_amount:'10000.00'}}])assert.throws(()=>contract.validateSurplusWorkspace({...projection,...change},{actorId:actor.user_id,kind:'credits',limit:50,offset:0}));});

test('first explicit own request rejects staff response and invalid mode never sends a read',async()=>{let reads=0;const client=createTreasuryClient({request:async()=>{reads++;return {...projection,mode:'staff'};}},{getSession:()=>session});await assert.rejects(client.surplusWorkspace({mode:'own'}));assert.equal(reads,1);await assert.rejects(client.surplusWorkspace({mode:'administrator'}));assert.equal(reads,1);client.dispose();});
