import test from 'node:test';
import assert from 'node:assert/strict';
import {Element,fire} from './helpers/dom.mjs';
import {mountCollectorRemittance,remittanceSummaryMarkup,validateCollectorRemittanceEvidence,collectorRemittanceResultMatches,renderCollectorRemittanceEvidence} from '../assets/collector-remittance.js';
import {createCollectorWriteGuard} from '../assets/collector-write-guard.js';
export const preview={collector_user_id:'collector',collection_date:'2026-10-02',total_amount:'115.00',transaction_count:2,payment_count:2,unable_to_pay_count:0,covered_payment_count:0,client_count:2,refund_due_release_count:1,refund_due_release_total:'35.00',items:[{transaction_id:'t1',client_id:'c1',loan_id:'l1',client_name:'One',loan_type:'Regular',collection_date:'2026-10-02',entry_type:'payment',amount:'100.00',receipt_number:'R1',accepted_at:'2026-10-02T01:00:00Z',note:'First',covered_dates:['2026-10-02']},{transaction_id:'t2',client_id:'c2',loan_id:'l2',client_name:'Two',loan_type:'7x7',collection_date:'2026-10-02',entry_type:'payment',amount:'50.00',receipt_number:'R2',accepted_at:'2026-10-02T01:00:00Z',note:'Second',covered_dates:[]}],refund_due_releases:[{release_id:'refund',approval_id:'approve',adjustment_id:'adjust',client_id:'c1',loan_id:'l1',client_name:'One',amount:'35.00',released_at:'2026-10-02T00:00:00Z',evidence_reference:'Evidence123',evidence_digest:'abc',cash_effect:'outflow'}]};
const session={user:{user_id:'collector'},permissions:['remittance.create','remittance.view']};
function harness({permissions=session.permissions,date='2026-10-02',response}={}){const root=new Element();const calls=[];const guard=createCollectorWriteGuard({eventTarget:new EventTarget(),onLock(){}});const handle=mountCollectorRemittance({root,api:{async request(path,options){calls.push({path,options});if(response)return response(path,options);if(path.endsWith('/recipients'))return [{user_id:'r',full_name:'Recipient'}];if(path.includes('/preview'))return preview;return [];}},getSession:()=>({...session,permissions}),getRouteDate:()=>date,guard,onSaved:async()=>{}});return {root,calls,guard,handle};}
test('route failure skips preview without zero summary',async()=>{const h=harness({date:null});await h.handle.refresh();assert.equal(h.calls.filter(c=>c.path.includes('/preview')).length,0);assert.match(h.root.textContent,/Route date unavailable/);assert.doesNotMatch(h.root.textContent,/₱0\.00/);h.handle.dispose();h.guard.dispose();});
test('history only never calls creation reads',async()=>{const h=harness({permissions:['remittance.view']});await h.handle.refresh();assert.deepEqual(h.calls.map(c=>c.path),['/api/v1/remittances']);assert.match(h.root.textContent,/history only/);h.handle.dispose();h.guard.dispose();});
test('create only does not call ungranted history',async()=>{const h=harness({permissions:['remittance.create']});await h.handle.refresh();assert.equal(h.calls.some(c=>c.path==='/api/v1/remittances'),false);h.handle.dispose();h.guard.dispose();});
test('explicit zero summary is real while missing summary unavailable',()=>{assert.match(remittanceSummaryMarkup({status:'ready',data:{total_amount:'0.00',transaction_count:0,client_count:0,unable_to_pay_count:0}}),/₱0\.00/);assert.match(remittanceSummaryMarkup({status:'ready',data:{}}),/unavailable/i);});
test('full evidence includes payments refunds and rejected reason without computing total',()=>{const html=renderCollectorRemittanceEvidence({...preview,status:'rejected',rejection_reason:'Office mismatch'},{history:true});for(const text of ['R1','R2','Evidence123','35.00','115.00','Office mismatch'])assert.ok(html.includes(text),text);});
test('missing arrays duplicate ids inconsistent count and malformed money are not reviewable',()=>{assert.equal(validateCollectorRemittanceEvidence(preview),true);for(const bad of [{...preview,items:null},{...preview,refund_due_releases:undefined},{...preview,transaction_count:1},{...preview,items:[preview.items[0],preview.items[0]]},{...preview,total_amount:'NaN'}])assert.equal(validateCollectorRemittanceEvidence(bad),false);});
test('complete returned identity and reviewed snapshot required',()=>{const matches=collectorRemittanceResultMatches({collectorId:'collector',recipientId:'r',collectionDate:'2026-10-02',preview});const record={...preview,remittance_id:'11111111-2222-4333-8444-555555555555',remittance_number:'N1',recipient_user_id:'r',status:'submitted'};assert.equal(matches(record),true);for(const bad of [{},{...record,remittance_id:'invalid'},{...record,recipient_user_id:'other'},{...record,collection_date:'2026-10-03'},{...record,status:'received'},{...record,total_amount:'114.00'},{...record,items:[{...preview.items[0],amount:'99.00'},preview.items[1]]}])assert.equal(matches(bad),false);});
test('malformed resolved submission locks once and preserves note',async()=>{let posts=0;const h=harness({response:(path,options)=>{if(options?.method){posts++;return {};}if(path.endsWith('/recipients'))return [{user_id:'r',full_name:'Recipient'}];if(path.includes('/preview'))return preview;return [];}});await h.handle.refresh();const form=h.root.querySelector('#collector-remittance-form');form.querySelector('[name="recipientUserId"]').value='r';form.querySelector('[name="note"]').value='Retain';form.querySelector('[name="reviewed"]').checked=true;fire(form,'change');fire(form,'submit');await new Promise(r=>setTimeout(r,5));assert.equal(posts,1);assert.equal(h.guard.locked,true);fire(form,'submit');await new Promise(r=>setTimeout(r,5));assert.equal(posts,1);assert.equal(form.querySelector('[name="note"]').value,'Retain');h.handle.dispose();h.guard.dispose();});

test('retry recipients preserves note and selected valid recipient but removed recipient requires explicit reselection',async()=>{let recipients=[{user_id:'r',full_name:'Recipient'}];const h=harness({response:path=>path.endsWith('/recipients')?recipients:path.includes('/preview')?preview:[]});await h.handle.refresh();const form=h.root.querySelector('#collector-remittance-form'),note=form.querySelector('[name="note"]'),recipient=form.querySelector('[name="recipientUserId"]');note.value='Retain';recipient.value='r';await h.handle.refresh('recipients');assert.strictEqual(form.querySelector('[name="note"]'),note);assert.equal(note.value,'Retain');assert.equal(recipient.value,'r');recipients=[{user_id:'other',full_name:'Other'}];await h.handle.refresh('recipients');assert.equal(recipient.value,'');assert.equal(form.querySelector('button[type="submit"]').disabled,true);h.handle.dispose();h.guard.dispose();});
test('recipient error differs from successful empty and never invents unavailable evidence zeros',async()=>{const failed=harness({response:path=>{if(path.endsWith('/recipients'))throw new Error('Not available');return path.includes('/preview')?preview:[];}});await failed.handle.refresh();assert.match(failed.root.textContent,/Recipients could not load/);assert.ok(failed.root.querySelector('[data-retry-recipients]'));failed.handle.dispose();failed.guard.dispose();const empty=harness({response:path=>path.includes('/preview')?preview:[]});await empty.handle.refresh();assert.match(empty.root.textContent,/No eligible remittance recipient/);empty.handle.dispose();empty.guard.dispose();});
test('late old date preview cannot overwrite new route date and disposal clears private evidence',async()=>{let routeDate='2026-10-02',resolve;const root=new Element(),guard=createCollectorWriteGuard({eventTarget:new EventTarget(),onLock(){}});const handle=mountCollectorRemittance({root,guard,getSession:()=>session,getRouteDate:()=>routeDate,onSaved:async()=>{},api:{request:path=>path.includes('/preview')?new Promise(r=>resolve=r):Promise.resolve([])}});const read=handle.refresh();routeDate='2026-10-03';resolve(preview);await read;assert.notEqual(handle.states.preview.status,'ready');assert.doesNotMatch(root.textContent,/115\.00/);handle.dispose();assert.equal(root.innerHTML,'');guard.dispose();});
test('65 remittance history rows remain reachable with complete saved details',async()=>{const records=Array.from({length:65},(_,i)=>({...preview,remittance_id:String(i),remittance_number:'N'+i,recipient_user_id:'r',status:'rejected',rejection_reason:'Office mismatch'}));const h=harness({response:path=>path.includes('/preview')?preview:path.endsWith('/recipients')?[{user_id:'r',full_name:'Recipient'}]:records});await h.handle.refresh();assert.match(h.root.textContent,/Showing 30 of 65/);fire(h.root.querySelector('[data-more-history]'),'click');assert.match(h.root.textContent,/Showing 60 of 65/);fire(h.root.querySelector('[data-more-history]'),'click');assert.match(h.root.textContent,/Showing 65 of 65/);assert.equal(await h.handle.openRecord('64'),true);assert.match(h.root.querySelector('[data-remittance-detail]').textContent,/Office mismatch/);h.handle.dispose();h.guard.dispose();});
