import test from 'node:test';
import assert from 'node:assert/strict';
import {Element,fire} from './helpers/dom.mjs';
import {mountCollectorWorkspace} from '../assets/roles/collector.js';
const entries=[{route_entry_id:'r1',loan_id:'l1',client_id:'c1',client_name:'First',loan_type:'Regular',area:'A',route_revision:'v1',can_enter_payment:true,contract_today_unpaid_amount:'100.00'},{route_entry_id:'r2',loan_id:'l2',client_id:'c2',client_name:'Second',loan_type:'7x7',area:'A',route_revision:'v1',can_enter_payment:true,contract_today_unpaid_amount:'50.00'}];
function document(){const doc=new EventTarget();doc.createElement=tag=>{const node=new Element(tag);node.ownerDocument=doc;return node;};doc.body=new Element('body');doc.activeElement=doc.body;return doc;}
const flush=async()=>{await new Promise(r=>setTimeout(r,5));};
async function harness(t,{response,permissions=['route.view','collection.create'],getSession}={}){const root=new Element();root.ownerDocument=document();const calls=[];let handle;const session={user:{user_id:'collector'},permissions};const original=globalThis.FormData;globalThis.FormData=class{constructor(form){this.form=form;}get(key){return this.form.querySelector(`[name="${key}"]`)?.value || '';}};t.after(()=>globalThis.FormData=original);const controller=new AbortController();t.after(()=>controller.abort());let nextSequence=0;const context={root,signal:controller.signal,session,getSession:getSession || (()=>session),setNavigation(){},activateNavigation(){},registerWorkspaceHandle(value){handle=value;},sessionStore:{deviceId:()=> 'd',nextDeviceSequence:()=>++nextSequence},api:{async request(path,options){calls.push({path,options});return response?response(path,options):path.endsWith('/routes/today')?{route_date:'2026-10-02',entries}:{};}}};await mountCollectorWorkspace(context);return {root,calls,context,get handle(){return handle;}};}
test('route renders independently while secondary reads are absent until activated',async t=>{const h=await harness(t);assert.ok(h.root.querySelector('.collector-entry-form'));assert.equal(h.calls.some(c=>c.path.includes('remittance')),false);assert.equal(h.calls.some(c=>c.path.includes('renewals')),false);assert.equal(h.calls.some(c=>c.path.includes('activity-notifications')),false);});
test('verified save retains unrelated note nodes and guard even if readback fails',async t=>{let routeReads=0,posts=0;const h=await harness(t,{response:(path,options)=>{if(options?.method){posts++;return {status:'accepted',client_transaction_id:options.body.client_transaction_id,receipt_number:'R1'};}if(path.endsWith('/routes/today')){if(routeReads++)throw new Error('Read failed');return {route_date:'2026-10-02',entries};}return {};}});const form=h.root.querySelector('[data-route-entry-id="r1"]'),other=h.root.querySelector('[data-route-entry-id="r2"]'),note=other.querySelector('[name="note"]');note.value='Retain after lunch';form.querySelector('[name="amount"]').value='100.00';form.querySelector('[name="entryType"]').value='payment';form.querySelector('[name="allocation"]').value='scheduled';const guard=h.context.collectorWriteGuard;fire(form,'submit');await flush();assert.equal(posts,1);assert.strictEqual(h.context.collectorWriteGuard,guard);assert.strictEqual(h.root.querySelector('[data-route-entry-id="r2"]').querySelector('[name="note"]'),note);assert.equal(note.value,'Retain after lunch');assert.match(h.root.textContent,/Saved.*could not refresh/i);assert.match(form.textContent,/Receipt R1/);fire(form,'submit');await flush();assert.equal(posts,1);});
test('changed revision or date keeps note but blocks stale direct command',async t=>{let reads=0;const h=await harness(t,{response:path=>path.endsWith('/routes/today')?{route_date:reads++?'2026-10-03':'2026-10-02',entries:reads>1?entries.map(e=>({...e,route_revision:'v2'})):entries}:{}});const form=h.root.querySelector('[data-route-entry-id="r2"]'),note=form.querySelector('[name="note"]');note.value='Keep';await h.handle.refreshVisible();assert.strictEqual(h.root.querySelector('[data-route-entry-id="r2"]').querySelector('[name="note"]'),note);assert.match(form.textContent,/Route changed/);fire(form,'submit');await flush();assert.equal(h.calls.filter(c=>c.options?.method).length,0);});
test('uncertain guard survives ordinary header refresh and performs no new read or write',async t=>{const h=await harness(t);const count=h.calls.length;h.context.collectorWriteGuard.lock('Uncertain');await h.handle.refreshVisible();assert.equal(h.calls.length,count);assert.equal(h.context.collectorWriteGuard.locked,true);});
