import test from 'node:test';import assert from 'node:assert/strict';import {Element,fire} from './helpers/dom.mjs';
const module=await import('../assets/collector-surplus.js').catch(()=>({}));
const id=n=>`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor={user_id:id(1),device_id:id(2)},session={user:{id:actor.user_id,role:'management',status:'active'},device_id:'install',device_registered:true,permissions:['treasury.collector_surplus.view']};
const base={collector_surplus_contract_version:1,actor,mode:'staff',readiness:{enabled:true,treasury_ready:true,application_enabled:false,application_supported:false,historical_correction_supported:false,gl_supported:false,blockers:[{code:'historical',message:'Historical correction adapter unavailable.'}]},capabilities:{view:true,count_record:true,count_accept:true,recognize:true,return_prepare:true,return_record:true,opening_prepare:true,opening_activate:true,exception_record:true},accounts:[{id:id(3),ledger_context_id:id(4),version:1,kind:'physical_cash',alias:'Synthetic counted cash',custodian_user_id:actor.user_id,actions:['count_record','count_accept','recognize','return_prepare','return_record','opening_prepare','opening_activate','exception_record']}],collector_choices:[{user_id:id(5),name:'Synthetic Collector'}],kind:'credits',items:[],total_count:0,totals:{outstanding_amount:'90071992547409.93'},has_more:false,limit:50,offset:0};

test('recipient selects a current held record and sees only additional cash required',async t=>{
 const root=new Element(),remittance=id(20),account=base.accounts[0];
 const exception={id:id(30),version:2,account_id:account.id,ledger_context_id:account.ledger_context_id,collector_user_id:id(5),remittance_id:remittance,status:'held_disputed',retained_amount:'9900.00',returned_amount:'0.00',included_amount:'0.00',reserved_amount:'0.00',remaining_held_amount:'9900.00',available_amount:'9900.00'};
 const preview={collector_surplus_contract_version:1,actor_user_id:actor.user_id,device_id:actor.device_id,account_id:account.id,account_version:1,ledger_context_id:account.ledger_context_id,remittance_id:remittance,collector_user_id:id(5),recipient_user_id:actor.user_id,source_digest:'a'.repeat(64),gross_obligation:'10000.00',refund_due_total:'0.00',authorized_credit_application:'0.00',physical_cash_required:'100.00',retained_cash_amount:'9900.00',retained_exception_id:exception.id,retained_exception_version:2,source_items:[],refund_due_releases:[],can_count:true,blockers:[]};
 let previewBody;
 const handle=module.mountCollectorSurplus({root,getSession:()=>session,remittanceId:remittance,api:{request:async(p,o)=>{
  if(p.endsWith('/preview')){previewBody=o.body;return preview;}
  if(p.includes('/exceptions/'))return exception;
  const kind=new URLSearchParams(p.split('?')[1]).get('kind');
  return {...base,kind,totals:{},items:kind==='exceptions'?[exception]:[{remittance_id:remittance,collector_user_id:id(5),total_amount:'10000.00'}],total_count:1};
 }}});t.after(handle);await handle.ready;
 const settle=async()=>{await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));};
 fire(root.querySelector('[data-surplus-navigation="exceptions"]'),'click');await settle();
 fire(root.querySelector('[data-surplus-navigation="remittances"]'),'click');await settle();
 const form=root.querySelector('[data-surplus-form="collector_count_record"]'),select=form.querySelector('[name="retained_exception_id"]');
 select.value=exception.id;fire(select,'change');await settle();
 fire(form.querySelector('[data-surplus-preview]'),'click');await settle();
 assert.equal(previewBody.retained_exception_id,exception.id);assert.equal(previewBody.retained_exception_version,2);
 assert.match(form.textContent,/Previously retained cash to include:.*9,900.00/);
 assert.match(form.textContent,/New physical cash required:.*100.00/);
 assert.match(form.textContent,/New cash counted now \(exclude previously retained cash\)/);
});
async function mount(t,{own=false}={}){assert.equal(typeof module.mountCollectorSurplus,'function');let live=session;const root=new Element(),calls=[],controller=new AbortController(),projection=own?{...base,mode:'own',accounts:[],collector_choices:[],capabilities:{view:true,return_request:true,return_acknowledge:true,application_request:true}}:base;const handle=module.mountCollectorSurplus({root,mode:own?'own':undefined,getSession:()=>live,signal:controller.signal,api:{request:async(p,o={})=>{calls.push({p,o});if(p.includes('/collector-surplus/workspace')){const q=new URLSearchParams(p.split('?')[1]);return {...projection,kind:q.get('kind'),offset:Number(q.get('offset')),limit:Number(q.get('limit'))};}if(p==='/api/v1/treasury/workspace')return {contract_version:1,actor,enabled:true,owner_configured:true,capabilities:{evidence_upload:true},accounts:[{...base.accounts[0],balance:null,actions:['evidence_upload','receipt_verify']}],claims:[],blockers:[]};return {items:[],total_count:0,totals:null,limit:50,offset:0,has_more:false};}}});t.after(handle);await handle.ready;return {root,handle,calls,revoke:()=>live=null,controller};}
test('staff count/credit/return/opening/exception forms exist and blocked adapters are explicit',async t=>{const h=await mount(t);for(const action of ['collector_count_record','collector_count_accept','collector_surplus_recognize','collector_surplus_return_prepare','collector_surplus_return_record','collector_surplus_opening_prepare','collector_surplus_opening_activate','collector_custody_exception_record','collector_surplus_return_reverse'])assert.ok(h.root.querySelector(`[data-surplus-form="${action}"]`),action);assert.match(h.root.textContent,/Historical correction adapter unavailable/);assert.doesNotMatch(h.root.textContent,/Application completed|Journal posted/);});
test('own credit shows server totals with no office approval/editor/history requests',async t=>{const h=await mount(t,{own:true});assert.match(h.root.textContent,/90,071,992,547,409.93/);assert.ok(h.root.querySelector('[data-surplus-form="collector_surplus_return_request"]'));assert.equal(h.root.querySelector('[data-surplus-account-label]').hidden,true);assert.equal(h.root.querySelector('[data-surplus-form="collector_surplus_recognize"]'),null);assert.equal(h.calls.some(x=>/\/accounts\/|\/events|\/treasury\/workspace$/.test(x.p)),false);});
test('refresh retains draft text and exact selected File nodes',async t=>{const h=await mount(t),form=h.root.querySelector('[data-surplus-form="collector_surplus_recognize"]'),node=form.querySelector('[name="amount"]'),file=h.root.querySelector('[data-surplus-file]');node.value='40.00';const selected=new Blob(['synthetic'],{type:'image/png'});file.files=[selected];await h.handle.refreshReadOnly();assert.equal(h.root.querySelector('[data-surplus-form="collector_surplus_recognize"]'),form);assert.equal(node.value,'40.00');assert.equal(h.root.querySelector('[data-surplus-file]'),file);assert.equal(file.files[0],selected);assert.equal(h.calls.some(x=>x.o.financial),false);});
test('scope change and abort remove all private draft and File state',async t=>{const h=await mount(t);h.revoke();await h.handle.refreshReadOnly();assert.equal(h.root.innerHTML,'');const second=await mount(t);second.controller.abort();assert.equal(second.root.innerHTML,'');});
test('private task opens under sharing stop and leaves safe server money unchanged',async()=>{assert.equal(typeof module.renderSurplusPage,'function');const html=module.renderSurplusPage({...base,total_count:200,items:[]});assert.match(html,/200/);assert.match(html,/90,071,992,547,409.93/);assert.match(html,/Server totals/);});

test('Collector role exposes a lazy own-credit task without office wallet calls',async t=>{const {mountCollectorWorkspace}=await import('../assets/roles/collector.js');const root=new Element(),calls=[],controller=new AbortController();t.after(()=>controller.abort());let handle;const current={...session,user:{...session.user,role:'collector'},permissions:['route.view']};await mountCollectorWorkspace({root,session:current,getSession:()=>current,signal:controller.signal,setNavigation(){},registerWorkspaceHandle:h=>handle=h,api:{request:async p=>{calls.push(p);if(p.includes('/collector-surplus/workspace')){const q=new URLSearchParams(p.split('?')[1]);return {...base,mode:'own',kind:q.get('kind'),accounts:[],collector_choices:[],capabilities:{view:true,return_request:true}};}return {route_date:'2026-10-02',entries:[],areas:[]};}}});assert.ok(root.querySelector('[data-collector-task="collector-surplus"]'));assert.equal(calls.some(p=>p.includes('/collector-surplus/')),false);await handle.activate('collector-surplus');assert.match(root.textContent,/My excess credit/);assert.ok(calls.some(p=>p.includes('mode=own')));assert.equal(calls.some(p=>p==='/api/v1/treasury/workspace'),false);});

test('preview click performs the actual read and retains editable actual count independently',async()=>{const root=new Element(),remittance=id(20),account=base.accounts[0],preview={collector_surplus_contract_version:1,actor_user_id:actor.user_id,device_id:actor.device_id,account_id:account.id,account_version:1,ledger_context_id:account.ledger_context_id,remittance_id:remittance,remittance_number:'SYN-COUNT',collector_user_id:id(5),recipient_user_id:actor.user_id,source_digest:'a'.repeat(64),gross_obligation:'10000.00',refund_due_total:'0.00',authorized_credit_application:'0.00',physical_cash_required:'10000.00',source_items:[{id:id(21),amount:'10000.00',collection_date:'2026-10-01'}],refund_due_releases:[],can_count:true,blockers:[]};const handle=module.mountCollectorSurplus({root,getSession:()=>session,remittanceId:remittance,api:{request:async(p)=>p.endsWith('/preview')?preview:{...base,kind:'remittances',items:[{remittance_id:remittance,id:remittance,collector_user_id:id(5),remittance_number:'SYN-COUNT',total_amount:'10000.00'}],totals:{}}}});await handle.ready;const form=root.querySelector('[data-surplus-form="collector_count_record"]');fire(form.querySelector('[data-surplus-preview]'),'click');await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve));assert.match(form.querySelector('[data-surplus-preview-result]').textContent,/10,000.00/);assert.match(form.querySelector('[data-surplus-preview-result]').textContent,/2026-10-01/);assert.doesNotMatch(root.querySelector('[data-surplus-status]').textContent,/not defined/);handle();});
test('first selected account is queried before displaying its server totals',async()=>{const root=new Element(),queries=[],second={...base.accounts[0],id:id(40),alias:'Second actual cash'},api={request:async(p)=>{const q=new URLSearchParams(p.split('?')[1]);queries.push(q.get('account_id'));return {...base,accounts:q.get('account_id')?[base.accounts[0]]:[...base.accounts,second],totals:{outstanding_amount:q.get('account_id')?'100.00':'9900.00'}};}};const handle=module.mountCollectorSurplus({root,api,getSession:()=>session});await handle.ready;assert.deepEqual(queries,[null,base.accounts[0].id]);assert.match(root.querySelector('[data-surplus-page]').textContent,/100.00/);assert.doesNotMatch(root.querySelector('[data-surplus-page]').textContent,/9,900.00/);handle();});

test('account selector retains every authorized choice while displayed records use only selected scope',async()=>{const root=new Element(),second={...base.accounts[0],id:id(40),alias:'Second actual cash'},queries=[];const handle=module.mountCollectorSurplus({root,getSession:()=>session,api:{request:async p=>{const q=new URLSearchParams(p.split('?')[1]),chosen=q.get('account_id');queries.push(chosen);return {...base,accounts:chosen?[chosen===second.id?second:base.accounts[0]]:[base.accounts[0],second],totals:{outstanding_amount:chosen===second.id?'200.00':'100.00'}};}}});await handle.ready;const select=root.querySelector('[data-surplus-account]');assert.equal(select.querySelectorAll('option').length,2);select.value=second.id;fire(select,'change');await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));assert.equal(queries.at(-1),second.id);assert.match(root.querySelector('[data-surplus-page]').textContent,/200.00/);handle();});
