import assert from 'node:assert/strict';import test from 'node:test';import {setImmediate} from 'node:timers/promises';import {Element,fire} from './helpers/dom.mjs';import {mountEmployeeWorkspace} from '../assets/roles/employee.js';import {workspace,SELF} from './helpers/employee-workspace.mjs';
test('secondary delay does not block Today, cash stays lazy, one workday read and one binding on revisit',async(t)=>{const root=new Element(),controller=new AbortController();let handle;const calls=[];const context={root,signal:controller.signal,session:{user:{id:SELF,role:'employee'},permissions:['cash_disbursement.prepare','support.manage','remittance.view']},setNavigation(){},registerWorkspaceHandle:value=>handle=value,api:{request:async(path)=>{calls.push(path);if(path==='/api/v1/employee-operations/workspace')return workspace();if(path==='/api/v1/activity-notifications')return new Promise(()=>{});if(path==='/api/v1/management/support?status=open')throw new Error('Unavailable');return [];}}};await mountEmployeeWorkspace(context);t.after(()=>controller.abort());await setImmediate();assert.ok(root.querySelector('[data-employee-attendance]'));assert.equal(calls.length,1);handle.activate('employee-updates');await setImmediate();assert.match(root.querySelector('[data-employee-today]').textContent,/No attendance record today/);handle.activate('employee-support');await setImmediate();assert.ok(root.querySelector('[data-employee-local-retry]'));assert.equal(root.querySelector('[data-cash-disbursement-form]'),null);handle.activate('employee-operations');fire(root.querySelector('[data-employee-create="leave_request"]'),'click');const form=root.querySelector('[data-employee-form]');form.querySelector('[name="reason"]').value='Retained draft';await handle.refreshVisible();assert.equal(root.querySelector('[data-employee-form]'),form);handle.activate('employee-payslips');assert.equal(root.querySelector('[data-employee-form]'),form);assert.equal(root.querySelector('[data-employee-operations]').parentElement,root.querySelector('[data-employee-payslips-slot]'));handle.activate('employee-operations');assert.equal(root.querySelector('[data-employee-form]'),form);});
test('65 loaded updates reveal all in server order and Today does not invent unread count',async(t)=>{const root=new Element(),controller=new AbortController();let handle;const items=Array.from({length:65},(_,index)=>({notification_id:String(index),title:`Update ${index}`,message:'Duplicate-looking activity'}));await mountEmployeeWorkspace({root,signal:controller.signal,session:{user:{id:SELF}},setNavigation(){},registerWorkspaceHandle:value=>handle=value,api:{request:async(path)=>path.includes('employee-operations')?workspace():items}});t.after(()=>controller.abort());handle.activate('employee-updates');await setImmediate();assert.equal(root.querySelectorAll('.timeline-item').length,50);assert.match(root.textContent,/Showing 50 of 65 loaded/);fire(root.querySelector('[data-employee-updates-more]'),'click');assert.equal(root.querySelectorAll('.timeline-item').length,65);assert.match(root.textContent,/Showing 65 of 65 loaded/);assert.match(root.querySelector('[data-employee-loaded-updates]').textContent,/not an unread count/);});
test('a stale shell handle clears the private Employee surface when its live identity changes',async(t)=>{const root=new Element(),controller=new AbortController();let handle;const context={root,signal:controller.signal,session:{user:{id:SELF}},setNavigation(){},registerWorkspaceHandle:value=>handle=value,api:{request:async()=>workspace()}};await mountEmployeeWorkspace(context);t.after(()=>controller.abort());await setImmediate();fire(root.querySelector('[data-employee-create="leave_request"]'),'click');const reason=root.querySelector('[name="reason"]');reason.value='Private draft';context.session={user:{id:'different'}};await handle.refreshVisible();assert.equal(root.innerHTML,'');assert.equal(reason.value,'');});

test('Today shortcuts select each existing work/pay view without extra reads or losing another draft',async t=>{
 const root=new Element(),controller=new AbortController();let handle;const calls=[];
 const context={root,signal:controller.signal,session:{user:{id:SELF}},setNavigation(){},registerWorkspaceHandle:value=>handle=value,navigateTo:id=>handle.activate(id),api:{async request(path){calls.push(path);return workspace();}}};
 await mountEmployeeWorkspace(context);t.after(()=>controller.abort());await setImmediate();
 fire(root.querySelector('[data-employee-create="leave_request"]'),'click');const form=root.querySelector('[data-employee-form]'),reason=form.querySelector('[name="reason"]');reason.value='Keep my leave explanation';
 for(const view of ['workday','tasks','timeoff','payslips']){handle.activate('employee-overview');const button=root.querySelector(`[data-employee-today-view="${view}"]`);assert.ok(button,view);fire(button,'click');assert.equal(root.querySelector(`[data-employee-view-button="${view}"]`).getAttribute('aria-pressed'),'true');assert.strictEqual(root.querySelector('[data-employee-form]'),form);assert.equal(reason.value,'Keep my leave explanation');}
 assert.equal(calls.length,1);
});
