import assert from 'node:assert/strict';import test from 'node:test';import * as workday from '../assets/employee-workday.js';
const employeeId='self';const event=(id,type,prior=null,device='device')=>({id,employee_id:employeeId,status:'accepted',payload:{event_type:type,captured_at:`2026-10-02T0${id}:00:00Z`,previous_event_id:prior,device_id:device,sequence:Number(id)+1}});
test('no event means no record and normal chain guides the next action without granting it',()=>{assert.deepEqual(workday.attendanceGuidance({events:[],employeeId,workDate:'2026-10-02'}),{label:'No attendance record today',primaryActions:['clock_in'],needsReview:false});const events=[event('1','clock_in'),event('2','break_start','1'),event('3','break_end','2')];assert.deepEqual(workday.attendanceGuidance({events,employeeId,workDate:'2026-10-02'}).primaryActions,['break_start','clock_out']);assert.equal(workday.attendanceGuidance({events:[...events,event('4','clock_out','wrong')],employeeId,workDate:'2026-10-02'}).needsReview,true);assert.equal(workday.attendanceGuidance({events:[event('1','clock_in'),event('2','clock_out','1','other')],employeeId,workDate:'2026-10-02'}).needsReview,true);});
test('Today excludes other staff, missing setup is unavailable, latest payroll uses period and status',()=>{const workspace={actor:{employee_id:employeeId},setup_missing:['rate'],attendance:[],tasks:[{employee_id:employeeId},{employee_id:'other'}],requests:[{employee_id:'other'}],payroll:[{id:'old',employee_id:employeeId,status:'paid',payload:{week_start:'2026-09-01'}},{id:'draft',employee_id:employeeId,status:'draft',payload:{week_start:'2026-10-01'}},{id:'new',employee_id:employeeId,status:'approved',payload:{week_start:'2026-09-28'}}]};const value=workday.buildEmployeeWorkdaySummary({workspace,now:new Date('2026-10-02T00:00:00Z')});assert.equal(value.workDate,'2026-10-02');assert.equal(value.tasks.records.length,1);assert.equal(value.requests.records.length,0);assert.equal(value.payroll.record.id,'new');assert.equal(value.payroll.status,'setup_incomplete');assert.equal(Object.hasOwn(value.payroll,'total'),false);});

test('own same-day server review remains separate from event guidance and blocks a clean suggestion',()=>{
 const workspace={actor:{employee_id:employeeId},attendance:[event('1','clock_in')],attendance_days:[{employee_id:'other',work_date:'2026-10-02',status:'accepted',issues:[]},{employee_id:employeeId,work_date:'2026-10-01',status:'accepted',issues:[]},{employee_id:employeeId,work_date:'2026-10-02',status:'pending_review',issues:['Incomplete attendance']}],tasks:[],requests:[],payroll:[]};
 const value=workday.buildEmployeeWorkdaySummary({workspace,now:'2026-10-02T00:00:00Z'});assert.equal(value.attendance.label,'Clock-in recorded');assert.equal(value.attendance.dayReview.record.status,'pending_review');assert.equal(value.attendance.needsReview,true);assert.deepEqual(value.attendance.primaryActions,[]);
 const absent=workday.buildEmployeeWorkdaySummary({workspace:{...workspace,attendance_days:[]},now:'2026-10-02T00:00:00Z'});assert.equal(absent.attendance.dayReview.status,'not_loaded');assert.equal(absent.attendance.needsReview,true);
 const nextDay=workday.buildEmployeeWorkdaySummary({workspace,now:'2026-10-02T16:00:00Z'});assert.equal(nextDay.workDate,'2026-10-03');assert.equal(nextDay.attendance.label,'No attendance record today');assert.equal(nextDay.attendance.dayReview.record,null);
});

test('rendered attendance guidance reflects server review and expires before another day action',async t=>{
 const {harness,workspace,SELF,DEVICE,ID,click}=await import('./helpers/employee-workspace.mjs');
 const originalAdd=globalThis.addEventListener,originalRemove=globalThis.removeEventListener,events=new EventTarget();
 globalThis.addEventListener=events.addEventListener.bind(events);globalThis.removeEventListener=events.removeEventListener.bind(events);
 t.after(()=>{globalThis.addEventListener=originalAdd;globalThis.removeEventListener=originalRemove;});
 let current=new Date('2026-10-02T00:00:00Z');const h=await harness(workspace(),{presentation:'employee',now:()=>current});t.after(h.dispose);
 assert.ok(h.root.querySelector('[data-employee-suggested="clock_in"]'));
 current=new Date('2026-10-02T16:00:00Z');events.dispatchEvent(new Event('focus'));
 assert.match(h.root.querySelector('[data-employee-guidance]').textContent,/Date changed.*refresh/i);assert.equal(h.root.querySelector('[data-employee-suggested]'),null);
 click(h,'[data-employee-attendance="clock_in"]');assert.equal(h.calls.some(c=>c.options.method==='POST'),false);
 h.value=workspace({attendance:[{id:ID,employee_id:SELF,status:'accepted',version:1,allowed_actions:[],payload:{event_type:'clock_in',captured_at:'2026-10-03T00:00:00+08:00',device_id:DEVICE,previous_event_id:null,sequence:1}}],attendance_days:[{employee_id:SELF,work_date:'2026-10-03',status:'pending_review',issues:['Incomplete shift']}]});await h.handle.refresh();
 assert.match(h.root.querySelector('[data-employee-guidance]').textContent,/Needs review/i);assert.equal(h.root.querySelector('[data-employee-suggested]'),null);assert.ok(h.root.querySelector('[data-employee-create="correction_request"]'));assert.equal(h.root.querySelectorAll('[data-employee-attendance]').length,4);
});
