import assert from 'node:assert/strict';import test from 'node:test';import * as printing from '../assets/employee-payslip-print.js';import {Element} from './helpers/dom.mjs';
const id='10000000-0000-4000-8000-000000000001',employee='20000000-0000-4000-8000-000000000001';
const record={id,employee_id:employee,version:3,status:'partially_paid',payload:{week_start:'2026-09-27',period_end:'2026-10-03',payroll_kind:'weekly',gross_pay:'12500.00',deductions:'500.00',net_pay:'12000.00',paid_amount:'4000.00',balance_due:'8000.00',issues:[],components:[{code:'basic_pay',label:'Basic <pay>',amount:'12500.00'},{code:'deduction',label:'Deduction',amount:'-500.00'}]}};
test('print projects exact server facts and labels partial/unpaid payroll without computing money',()=>{const markup=printing.buildPayslipPrintMarkup({record,employeeName:'Synthetic Employee'});for(const text of ['12500.00','500.00','12000.00','4000.00','8000.00','-500.00','Basic &lt;pay&gt;','not proof of payment'])assert.ok(markup.includes(text),text);for(const altered of [{status:'draft'},{payload:{...record.payload,issues:['Blocking review']}},{payload:{...record.payload,net_pay:null}}])assert.throws(()=>printing.buildPayslipPrintMarkup({record:{...record,...altered},employeeName:'Employee'}));});
test('fresh scope membership and original version control one isolated region, cleanup erases private text',async(t)=>{const root=new Element();let current={userId:employee,employeeId:employee,deviceId:id},value={actor:{user_id:employee,employee_id:employee,device_id:id},payroll:[record],profiles:[{employee_id:employee,payload:{full_name:'Synthetic Employee'}}]};let prints=0;const controller=new AbortController();const handle=printing.mountEmployeePayslipPrint({root,getCurrentScope:()=>current,loadWorkspace:async()=>value,signal:controller.signal,print:()=>prints++});t.after(handle.dispose);await handle.open(id,3);assert.equal(prints,1);assert.match(root.textContent,/Synthetic Employee/);handle.close();assert.equal(root.textContent,'');value={...value,payroll:[{...record,version:4}]};await assert.rejects(handle.open(id,3),/changed/i);assert.equal(prints,1);value={...value,payroll:[record]};current={...current,employeeId:id};await assert.rejects(handle.open(id,3),/scope|authorized/i);assert.equal(root.textContent,'');});

test('pagehide or history navigation erases print data and cancels a pending print read',async t=>{
 const events=new EventTarget(),add=globalThis.addEventListener,remove=globalThis.removeEventListener;
 globalThis.addEventListener=events.addEventListener.bind(events);globalThis.removeEventListener=events.removeEventListener.bind(events);t.after(()=>{globalThis.addEventListener=add;globalThis.removeEventListener=remove;});
 const root=new Element(),scope={userId:employee,employeeId:employee,deviceId:id},value={actor:{user_id:employee,employee_id:employee,device_id:id},payroll:[record],profiles:[]};let prints=0,resolve,delayed=false;
 const handle=printing.mountEmployeePayslipPrint({root,getCurrentScope:()=>scope,loadWorkspace:()=>delayed?new Promise(done=>resolve=done):Promise.resolve(value),print:()=>prints++});t.after(handle.dispose);
 await handle.open(id,3);assert.ok(root.querySelector('[data-employee-print-region]'));events.dispatchEvent(new Event('pagehide'));assert.equal(root.querySelector('[data-employee-print-region]'),null);
 delayed=true;const pending=handle.open(id,3);events.dispatchEvent(new Event('popstate'));resolve(value);await pending;assert.equal(prints,1);assert.equal(root.querySelector('[data-employee-print-region]'),null);
});
test('work/pay navigation and failed authorized refresh clear the mounted private payslip copy',async t=>{
 const {harness,workspace,SELF,click}=await import('./helpers/employee-workspace.mjs');
 const prior=globalThis.print;globalThis.print=()=>{};t.after(()=>globalThis.print=prior);
 const h=await harness(workspace({payroll:[{...record,employee_id:SELF,allowed_actions:[]}]}),{presentation:'employee'});t.after(h.dispose);
 h.handle.selectView('payslips');click(h,'[data-employee-print-payroll]');await new Promise(done=>setImmediate(done));assert.ok(h.root.querySelector('[data-employee-print-region]'));
 h.handle.selectView('tasks');assert.equal(h.root.querySelector('[data-employee-print-region]'),null);
 h.handle.selectView('payslips');click(h,'[data-employee-print-payroll]');await new Promise(done=>setImmediate(done));assert.ok(h.root.querySelector('[data-employee-print-region]'));
 h.readError=Object.assign(Error('Synthetic denied payroll'),{status:403});await h.handle.refresh();assert.equal(h.root.querySelector('[data-employee-print-region]'),null);assert.doesNotMatch(h.root.textContent,/12500.00|payroll record copy/);
});
