import assert from 'node:assert/strict';import test from 'node:test';import {fire} from './helpers/dom.mjs';import {harness,workspace,SELF,ID,click} from './helpers/employee-workspace.mjs';
test('six local views retain all records/actions, current loaded date filters twelve days and self cancellation omits paid minutes',async(t)=>{const request={id:ID,employee_id:SELF,version:3,status:'pending',allowed_actions:['request_decide'],payload:{request_kind:'leave',reason:'Own request'}};const days=Array.from({length:12},(_,index)=>({employee_id:SELF,work_date:`2026-10-${String(index+1).padStart(2,'0')}`,status:'accepted',working_minutes:480,unpaid_break_minutes:0,issues:[]}));const h=await harness(workspace({requests:[request],attendance_days:days}),{presentation:'employee'});t.after(h.dispose);assert.equal(h.root.querySelectorAll('[data-employee-view-button]').length,6);assert.equal(h.root.querySelector('[data-employee-collection="requests"]').hidden,true);h.handle.selectView('timeoff');assert.equal(h.root.querySelector('[data-employee-collection="requests"]').hidden,false);assert.match(h.root.querySelector('[data-employee-action="request_decide"]').textContent,/Cancel my request/);click(h,'[data-employee-action="request_decide"]');const form=h.root.querySelector('[data-employee-form]');assert.equal(form.querySelector('[name="paid_minutes"]'),null);assert.doesNotMatch(form.innerHTML,/value="approved"/);h.handle.selectView('workday');assert.equal(h.root.querySelector('[data-employee-form]'),form);assert.doesNotMatch(h.root.querySelector('[data-employee-attendance-days]').textContent,/2026-10-12/);click(h,'[data-employee-all-dates]');assert.match(h.root.querySelector('[data-employee-attendance-days]').textContent,/2026-10-12/);assert.equal(h.root.querySelector('[data-employee-form]'),form);});
test('Time off and Workday create buttons belong to their distinct local views',async(t)=>{const h=await harness(workspace(),{presentation:'employee'});t.after(h.dispose);h.handle.selectView('timeoff');assert.equal(h.root.querySelector('[data-employee-create="leave_request"]').closest('[data-employee-view]').hidden,false);assert.equal(h.root.querySelector('[data-employee-create="correction_request"]').closest('[data-employee-view]').hidden,true);h.handle.selectView('workday');assert.equal(h.root.querySelector('[data-employee-create="correction_request"]').closest('[data-employee-view]').hidden,false);});

const OTHER='20000000-0000-4000-8000-000000000002';
const row=(id,employee_id,payload={},allowed_actions=[])=>({id,employee_id,version:1,status:'pending',payload,allowed_actions});
test('personal work summary uses own latest facts without hiding authorized reviewer records',async(t)=>{
 const value=workspace({attendance_days:[{employee_id:OTHER,work_date:'2026-10-15',issues:[]},{employee_id:SELF,work_date:'2026-10-01',issues:[]},{employee_id:SELF,work_date:'2026-10-02',issues:[]}],leave_balances:[{employee_id:OTHER,as_of:'2026-10-03',available_minutes:999},{employee_id:SELF,as_of:'2026-10-01',available_minutes:120},{employee_id:SELF,as_of:'2026-10-02',available_minutes:240}],requests:[row(ID,OTHER,{reason:'Other visible request'}),row(OTHER,SELF,{reason:'My request'})],tasks:[row(ID,OTHER,{description:'Other visible task'})]});
 const h=await harness(value,{presentation:'employee'});t.after(h.dispose);
 const cards=h.root.querySelector('[data-employee-work-summary]').querySelectorAll('article');
 assert.deepEqual(cards.map(card=>card.querySelector('strong').textContent),['2026-10-02','240 min available','1','0','0','0']);
 h.handle.selectView('timeoff');assert.match(h.root.querySelector('[data-employee-collection="requests"]').textContent,/Other visible request/);
 h.handle.selectView('tasks');assert.match(h.root.querySelector('[data-employee-collection="tasks"]').textContent,/Other visible task/);
});
test('selected attendance date clearly reports loaded zero and All loaded dates restores original days',async(t)=>{
 const h=await harness(workspace({attendance_days:[{employee_id:SELF,work_date:'2026-10-01',status:'accepted',issues:[],working_minutes:480,unpaid_break_minutes:0}]}),{presentation:'employee'});t.after(h.dispose);
 assert.match(h.root.querySelector('[data-employee-date-empty]')?.textContent||'',/No record for this date/);
 click(h,'[data-employee-all-dates]');assert.equal(h.root.querySelector('[data-employee-date-empty]'),null);assert.match(h.root.textContent,/2026-10-01/);
 click(h,'[data-employee-all-dates]');const from=h.root.querySelector('[name="attendanceFrom"]');from.value='2026-10-04';fire(from,'change');const to=h.root.querySelector('[name="attendanceTo"]');to.value='2026-10-05';fire(to,'change');assert.match(h.root.querySelector('[data-employee-date-empty]').textContent,/No records for this date range/);
 const empty=await harness(workspace(),{presentation:'employee'});t.after(empty.dispose);assert.match(empty.root.querySelector('[data-employee-date-empty]')?.textContent||'',/No record for this date/);assert.doesNotMatch(empty.root.querySelector('[data-employee-date-empty]').textContent,/absent|unpaid/i);
});
test('record actions carry stable record identity and keep exact target after a reordered refresh',async(t)=>{
 const records=[row(ID,SELF,{description:'First task'},['task_progress']),row(OTHER,SELF,{description:'Second task'},['task_progress'])];
 const h=await harness(workspace({tasks:records}),{presentation:'employee'});t.after(h.dispose);h.handle.selectView('tasks');
 assert.equal(h.root.querySelector('[data-employee-action="task_progress"]').getAttribute('data-employee-record'),`tasks:${ID}`);
 h.value={...h.value,tasks:[records[1],records[0]]};await h.handle.refresh();
 click(h,`[data-employee-record="tasks:${OTHER}"]`);const form=h.root.querySelector('[data-employee-form]');form.querySelector('[name="status"]').value='done';form.querySelector('[name="reason"]').value='Finished the selected task';fire(form,'submit');await new Promise(resolve=>setImmediate(resolve));assert.equal(h.calls.find(call=>call.options.method==='POST').options.body.id,OTHER);
});
test('proposed advance repayments use labeled mobile facts with exact dates and long amounts',async(t)=>{
 const h=await harness(workspace({advances:[row(ID,SELF,{installments:[{due_date:'2026-10-04',amount:'1.01'}],proposed_terms:{reason:'Later dates',employee_acknowledgment:'Agreed',payroll_authorization:'Authorized',installments:[{due_date:'2026-10-05',amount:'9007199254740993.01'}]}})]}),{presentation:'employee'});t.after(h.dispose);
 const card=h.root.querySelector('[data-employee-proposed-installments]');assert.ok(card);assert.equal(card.querySelector('table'),null);assert.match(card.textContent,/Proposed due date/);assert.match(card.textContent,/2026-10-05/);assert.match(card.textContent,/9,007,199,254,740,993.01/);assert.match(card.textContent,/Proposed installment/);
});
