import test from 'node:test';
import assert from 'node:assert/strict';
import {setImmediate} from 'node:timers/promises';
import {Element,fire} from './helpers/dom.mjs';
import {workspace,SELF} from './helpers/employee-workspace.mjs';
import {mountEmployeeWorkspace} from '../assets/employee-workspace.js';
const items=Array.from({length:65},(_,index)=>({notification_id:`note-${index}`,title:'Similar update',message:`Private synthetic event ${index}`}));
async function mounted(t){const root=new Element(),controller=new AbortController();let handle,error=null,value=items;const calls=[];await mountEmployeeWorkspace({root,signal:controller.signal,session:{user:{id:SELF}},setNavigation(){},registerWorkspaceHandle:h=>handle=h,api:{async request(path){calls.push(path);if(path.includes('employee-operations'))return workspace();if(error)throw error;return value;}}});t.after(()=>controller.abort());handle.activate('employee-updates');await setImmediate();return{root,handle,calls,setError:next=>error=next,setValue:next=>value=next};}
test('Show more retains original rows and focus lands on loaded count when complete',async t=>{const h=await mounted(t),before=h.root.querySelectorAll('.timeline-item'),more=h.root.querySelector('[data-employee-updates-more]');assert.equal(before.length,50);fire(more,'click');const after=h.root.querySelectorAll('.timeline-item');assert.equal(after.length,65);assert.strictEqual(after[0],before[0]);assert.deepEqual(after.map(row=>row.getAttribute('data-employee-update-id')),items.map(item=>item.notification_id));assert.equal(h.root.querySelector('[data-employee-updates-count]').focused,true);assert.match(h.root.querySelector('[data-employee-loaded-updates]').textContent,/65 loaded.*not an unread count/);assert.equal(h.calls.length,2);});
for(const status of [401,403])test(`denied Updates ${status} clears all private items and stale Show more cannot restore them`,async t=>{const h=await mounted(t),old=h.root.querySelector('[data-employee-updates-more]');h.setError(Object.assign(Error('Synthetic denied Updates'),{status}));await h.handle.refreshVisible();assert.match(h.root.querySelector('[data-employee-updates]').textContent,/Updates access is unavailable/);assert.equal(h.root.querySelector('[data-employee-local-retry]'),null);assert.doesNotMatch(h.root.querySelector('[data-employee-loaded-updates]').textContent,/65/);fire(old,'click');await h.handle.refreshVisible();assert.doesNotMatch(h.root.textContent,/Private synthetic event/);assert.equal(h.calls.length,3);});
test('empty, failed and recovered Updates remain distinct without stale More callbacks',async t=>{const h=await mounted(t),old=h.root.querySelector('[data-employee-updates-more]');h.setError(Object.assign(Error('Synthetic transient read failure'),{status:503}));await h.handle.refreshVisible();assert.ok(h.root.querySelector('[data-employee-local-retry]'));assert.doesNotMatch(h.root.querySelector('[data-employee-updates]').textContent,/No Employee update/);fire(old,'click');assert.ok(h.root.querySelector('[data-employee-local-retry]'));h.setError(null);h.setValue([]);fire(h.root.querySelector('[data-employee-local-retry]'),'click');await setImmediate();assert.match(h.root.querySelector('[data-employee-updates]').textContent,/No Employee update/);assert.match(h.root.querySelector('[data-employee-loaded-updates]').textContent,/0 loaded/);});
