import assert from 'node:assert/strict';
import test from 'node:test';
import {fire} from './helpers/dom.mjs';
import {id,row,tick,setup,session} from './helpers/management-renewal-fixture.mjs';
const approved = (overrides={}) => row(1,{status:'approved',approved_principal:'10000.00',client_decision:'accepted',signer_readiness_status:'ready',activation_status:'released_pending_management',...overrides});
const released = (overrides={}) => approved({amount_locked_at:'2026-10-02T01:00:00Z',renewal_offset_amount:'1500.00',net_release_amount:'8500.00',new_loan_id:id(800),cash_released_to_collector_at:'2026-10-02T01:00:00Z',cash_given_to_client_at:'2026-10-02T02:00:00Z',handover_proof_status:'under_review',...overrides});
const png = () => new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAwAAAAICAIAAABChommAAAAFUlEQVR4nGNMmXaCgRBgIqhi2CsCAA7uAdJbOL7FAAAAAElFTkSuQmCC','base64')],{type:'image/png'});
async function open(item, write=async()=>({}), extras={}) {const calls=[];let blob=png();const api={async request(path,options){calls.push([path,options]);if(options?.method==='POST')return write(path,options);if(options?.responseType==='blob')return blob;return {requests:path.endsWith('status=approved')?[item]:[]};}};const value=await setup(api,extras);await value.handle.refresh({status:'approved'});return {...value,calls,setBlob:value=>{blob=value;}};}
async function clickConfirm(root,button){fire(button,'click');await tick();root.querySelector('[data-renewal-confirm-ack]').checked=true;fire(root.querySelector('[data-renewal-confirm-action]'),'click');await tick();}
async function view(root){fire(root.querySelector('[data-renewal-photo]'),'click');await tick();}
async function review(root,decision='approved'){const form=root.querySelector('[data-renewal-proof]');form.querySelector('[name="decision"]').value=decision;form.querySelector('[name="note"]').value='Reviewed actual handover';fire(form,'submit');await tick();const ack=root.querySelector('[data-renewal-confirm-ack]');assert.ok(ack);ack.checked=true;fire(root.querySelector('[data-renewal-confirm-action]'),'click');await tick();}

test('release checks server execution with no invented body or local cash arithmetic',async()=>{const {root,handle,calls}=await open(approved(),async()=>({request:released({cash_given_to_client_at:null,handover_proof_status:'not_submitted'})}));assert.match(root.textContent,/Pre-lock|pre-lock/);await clickConfirm(root,root.querySelector('[data-renewal-action="release-to-collector"]'));const posts=calls.filter(([,o])=>o?.method==='POST');assert.equal(posts.length,1);assert.equal(posts[0][1].body,undefined);assert.equal(handle.isWritePending(),false);assert.match(root.textContent,/1,500.00/);assert.match(root.textContent,/8,500.00/);handle.dispose();});
test('missing execution gets real server blocker; unavailable readiness never enables a release',async()=>{const {root,handle,calls}=await open(approved(),async()=>{throw Object.assign(new Error('internal detail'),{status:409,code:'renewal_execution_evidence_required'});});await clickConfirm(root,root.querySelector('[data-renewal-action="release-to-collector"]'));assert.match(root.textContent,/authoritative renewal execution/);assert.doesNotMatch(root.textContent,/internal detail/);assert.equal(handle.isWritePending(),false);assert.equal(calls.filter(([,o])=>o?.method==='POST').length,1);handle.dispose();const blocked=await open(approved({signer_readiness_status:null}));assert.equal(blocked.root.querySelector('[data-renewal-action="release-to-collector"]').disabled,true);blocked.handle.dispose();});
test('proof approval may activate once; CIF block is saved review with separate blocker',async()=>{for(const active of [true,false]){const item=released({client_cash_confirmed_at:'2026-10-02T03:00:00Z'});const {root,handle,calls}=await open(item,async()=>({request:{...item,handover_proof_status:'approved',activation_status:active?'active':'released_pending_management',ready_for_activation:false},...(active?{}:{message:'CIF needs review'})}));await view(root);assert.ok(root.querySelector('img'));await review(root);assert.equal(handle.isWritePending(),false);assert.match(root.textContent,/Photo review saved/);assert.match(root.textContent,active?/Renewal is active/:/CIF/);assert.equal(calls.filter(([p,o])=>o?.method==='POST').length,1);assert.equal(calls.filter(([p,o])=>o?.method==='POST'&&p.endsWith('/activate')).length,0);handle.dispose();}});
test('actual proof remains reviewable when signers or office state separately block activation',async()=>{const item=released({signer_readiness_status:'pending',office_processing_required:true});const {root,handle}=await open(item,async()=>({request:{...item,handover_proof_status:'approved',ready_for_activation:false}}));await view(root);assert.equal(root.querySelector('[data-renewal-proof]').querySelector('button').disabled,false);await review(root);assert.match(root.textContent,/Photo review saved/);assert.equal(root.querySelector('[data-renewal-action="activate"]').disabled,true);handle.dispose();});
test('changed latest photo invalidates review; private URLs revoke on switch and disposal',async()=>{const originalCreate=URL.createObjectURL,originalRevoke=URL.revokeObjectURL;const revoked=[];URL.createObjectURL=()=> 'blob:synthetic-private';URL.revokeObjectURL=url=>revoked.push(url);try{const {root,handle,calls,setBlob}=await open(released());await view(root);assert.equal(root.querySelector('img').getAttribute('src'),'blob:synthetic-private');setBlob(new Blob([new Uint8Array([137,80,78,71,13,10,26,10,1])],{type:'image/png'}));const form=root.querySelector('[data-renewal-proof]');fire(form,'submit');await tick();assert.equal(root.querySelector('[data-renewal-confirm-action]'),null);assert.equal(root.querySelector('img'),null);assert.equal(calls.filter(([,o])=>o?.method==='POST').length,0);assert.deepEqual(revoked,['blob:synthetic-private']);await view(root);handle.dispose();assert.equal(revoked.length,2);}finally{URL.createObjectURL=originalCreate;URL.revokeObjectURL=originalRevoke;}});
test('unsupported private photo and a denied photo cannot create a reviewable image',async()=>{const {root,handle,setBlob}=await open(released());setBlob(new Blob(['fake'],{type:'text/html'}));await view(root);assert.equal(root.querySelector('img'),null);const form=root.querySelector('[data-renewal-proof]');fire(form,'submit');await tick();assert.equal(root.querySelector('[data-renewal-confirm-action]'),null);handle.dispose();});
test('unknown proof result remains blocked during read reconciliation and never POSTs again',async()=>{const {root,handle,calls}=await open(released(),async()=>({}));await view(root);await review(root);assert.equal(handle.isWritePending(),true);fire(root.querySelector('[data-renewal-reconcile]'),'click');await tick();assert.equal(handle.isWritePending(),true);assert.equal(await handle.refresh(),false);assert.equal(calls.filter(([,o])=>o?.method==='POST').length,1);handle.dispose();});
test('explicit activation is separate, has no body, and cannot sign or confirm client cash',async()=>{const item=released({handover_proof_status:'approved',ready_for_activation:true,client_cash_confirmed_at:'2026-10-02T03:00:00Z'});const {root,handle,calls}=await open(item,async()=>({request:{...item,activation_status:'active'}}));await clickConfirm(root,root.querySelector('[data-renewal-action="activate"]'));const posts=calls.filter(([,o])=>o?.method==='POST');assert.equal(posts.length,1);assert.match(posts[0][0],/\/management\/renewals\/.+\/activate$/);assert.equal(posts[0][1].body,undefined);assert.equal(handle.isWritePending(),false);assert.doesNotMatch(root.innerHTML,/cash-confirm|\/sign|\/client\/renewals/);handle.dispose();});
