import assert from 'node:assert/strict';
import test from 'node:test';
import {fire} from './helpers/dom.mjs';
import {id,row,tick,setup,fill,confirm,approved} from './helpers/management-renewal-fixture.mjs';

test('rich queue uses three real capped status paths and no legacy approval',async()=>{const paths=[];const {root,handle}=await setup({async request(path){paths.push(path);return {requests:[row(1,{status: new URL('https://synthetic'+path).searchParams.get('status')})]};}});assert.match(root.textContent,/200/);for(const status of ['approved','rejected'])assert.equal(await handle.refresh({status}),true);assert.deepEqual(paths,['pending','approved','rejected'].map(s=>'/api/v1/management/renewal-workflow?status='+s));handle.dispose();});
test('terms keep exact decimal text and unchecked verification flags; only local saved row changes',async()=>{const items=[row(1),row(2)],writes=[];const {root,handle}=await setup({async request(path,opts){if(opts?.method==='POST'){writes.push([path,opts]);return {request:approved(items[0],opts.body)};}return {requests:items};}});const other=fill(root,1);other.querySelector('[name="review_note"]').value='Other unsent draft';const form=fill(root);await confirm(root,form);assert.equal(writes.length,1);assert.match(writes[0][0],/\/terms$/);assert.equal(writes[0][1].body.approved_principal,'10000.00');assert.equal(writes[0][1].body.signers[0].government_id_verified,false);assert.equal(writes[0][1].body.signers[0].selfie_verified,false);assert.equal(root.querySelectorAll('[data-renewal-terms]').at(-1),other);assert.match(root.textContent,/Terms saved/);handle.dispose();});
test('recommendation, override, borrower account and signer review are never inferred',async()=>{for(const overrides of [{collector_recommendation:null},{collector_recommendation:'do_not_recommend'}]){let posts=0;const {root,handle}=await setup({async request(p,o){if(o?.method)posts++;return {requests:[row(1,overrides)]};}});const form=fill(root);fire(form,'submit');await tick();assert.equal(posts,0);assert.equal(root.querySelector('[data-renewal-confirm-action]'),null);handle.dispose();}});
test('malformed result locks terms across refresh, filter, record selection and duplicate clicks',async()=>{let posts=0;const {root,handle}=await setup({async request(p,o){if(o?.method){posts++;return {};}return {requests:[row()]};}});const form=fill(root);await confirm(root,form);assert.equal(handle.isWritePending(),true);assert.equal(await handle.refresh({status:'approved'}),false);assert.equal(handle.openRecord(id(1)),false);fire(form,'submit');await tick();assert.equal(posts,1);fire(root.querySelector('[data-renewal-reconcile]'),'click');await tick();assert.equal(handle.isWritePending(),true);assert.equal(posts,1);handle.dispose();});
test('fresh changed terms and edits during preflight cannot POST',async()=>{let changed=false,posts=0;const {root,handle}=await setup({async request(p,o){if(o?.method)posts++;return {requests:[row(1,{requested_amount:changed?'12000.00':'10000.00'})]};}});const form=fill(root);fire(form,'submit');await tick();changed=true;root.querySelector('[data-renewal-confirm-ack]').checked=true;fire(root.querySelector('[data-renewal-confirm-action]'),'click');await tick();assert.equal(posts,0);assert.match(root.textContent,/changed/);handle.dispose();});
test('result matcher rejects wrong request/client/loan/status/amount and empty object',async()=>{const {mod,handle}=await setup({async request(){return {requests:[]};}});const command={action:'terms',request:row(),body:{decision:'approved',approved_principal:'90071992547409.91',review_note:'Reviewed',override_reason:'',office_processing_required:true,signers:[]}};const good=approved(row(),command.body);assert.equal(mod.renewalResultMatches(command,{request:good}),true);for(const response of [{},{request:{...good,request_id:id(8)}},{request:{...good,client_id:id(9)}},{request:{...good,loan_id:id(9)}},{request:{...good,status:'rejected'}},{request:{...good,approved_principal:'90071992547409.92'}}])assert.equal(mod.renewalResultMatches(command,response),false);handle.dispose();});
