import assert from 'node:assert/strict';
import test from 'node:test';
import {createOfficeCaseContext} from '../assets/office-case-context.js';
const saved={mode:'saved-case',intakeReference:'INTAKE-A',applicantId:'applicant-a',clientId:'client-a'};
function setup(confirmDiscard=()=>true){let session={user:{id:'owner',role:'employee'},access_token:'first'};const changes=[];const c=createOfficeCaseContext({getSession:()=>session,confirmDiscard,onChange:value=>changes.push(value)});return {c,changes,setSession:value=>session=value};}
test('navigation retains dirty owners and does not reset or read',async()=>{const {c}=setup();let resets=0,reads=0;c.registerStage('intake',{isDirty:()=>true,resetCase:()=>resets++,openCase:()=>reads++});assert.equal(await c.requestTransition({kind:'navigate',targetStage:'cif'}),true);assert.equal(c.getContext().activeStage,'cif');assert.equal(resets,0);assert.equal(reads,0);});
test('replacement checks write locks before invoking a read or discard',async()=>{const {c}=setup(()=>assert.fail('locked work cannot be discarded'));let reads=0;c.registerStage('intake',{isWritePending:()=>true});assert.equal(await c.requestTransition({kind:'open',candidate:()=>{reads++;return saved;}}),false);assert.equal(reads,0);});
test('cancelled discard preserves verified context and stage owners',async()=>{const {c}=setup(()=>false);c.acceptVerifiedContext(saved,c.getGeneration());let resets=0;c.registerStage('intake',{isDirty:()=>true,resetCase:()=>resets++});assert.equal(await c.requestTransition({kind:'new-intake'}),false);assert.equal(c.getContext().intakeReference,'INTAKE-A');assert.equal(resets,0);});
test('new edits during discard make prior consent stale',async()=>{let resolve;const {c}=setup(()=>new Promise(done=>resolve=done));c.acceptVerifiedContext(saved,c.getGeneration());let resets=0;c.registerStage('intake',{isDirty:()=>true,resetCase:()=>resets++});const transition=c.requestTransition({kind:'close'});await Promise.resolve();c.invalidateCandidate();resolve(true);assert.equal(await transition,false);assert.equal(resets,0);assert.equal(c.getContext().intakeReference,'INTAKE-A');});
test('owner changes dispose owners while token refresh retains context',()=>{const {c,setSession}=setup();let disposed=0;c.registerStage('intake',{dispose:()=>disposed++});c.acceptVerifiedContext(saved,c.getGeneration());setSession({user:{id:'owner',role:'employee'},access_token:'refreshed'});assert.equal(c.getContext().intakeReference,'INTAKE-A');setSession({user:{id:'other',role:'employee'}});assert.equal(c.getContext().mode,'none');assert.equal(disposed,1);});
test('stale verified facts and cross-client application facts cannot change the case',()=>{const {c}=setup();c.acceptVerifiedContext(saved,c.getGeneration());const old=c.getGeneration();c.invalidateCandidate();assert.equal(c.acceptVerifiedContext({...saved,intakeReference:'INTAKE-B'},old),false);assert.equal(c.acceptVerifiedContext({...saved,clientId:'client-b',applicationReference:'APP-B',applicationSaved:true},c.getGeneration()),false);assert.equal(c.getContext().clientId,'client-a');});
test('explicit replacement detaches downstream saved and draft identities',async()=>{const {c}=setup();c.acceptVerifiedContext({...saved,applicationReference:'DRAFT-A',applicationSaved:false},c.getGeneration());assert.equal(await c.requestTransition({kind:'new-intake',targetStage:'intake'}),true);assert.equal(c.getContext().mode,'new-intake');assert.equal(c.getContext().intakeReference,null);assert.equal(c.getContext().applicationReference,null);});
test('denied candidate disposes private owners and returns false',async()=>{const {c}=setup();c.acceptVerifiedContext(saved,c.getGeneration());let disposals=0;c.registerStage('intake',{dispose:()=>disposals++});assert.equal(await c.requestTransition({kind:'open',candidate:async()=>{throw Object.assign(Error('Denied'),{status:403});}}),false);assert.equal(disposals,1);assert.equal(c.getContext().mode,'none');});
