import assert from 'node:assert/strict';
import test,{afterEach} from 'node:test';
import {setImmediate} from 'node:timers/promises';
import {Element,fire} from './helpers/dom.mjs';
import {mountOfficeApplicationFinder} from '../assets/office-application-finder.js';
const id='11111111-1111-4111-8111-111111111111',client='22222222-2222-4222-8222-222222222222',app='33333333-3333-4333-8333-333333333333',version='44444444-4444-4444-8444-444444444444';
const row=(ref='INT/A')=>({applicant_id:id,intake_reference:ref,client_id:client,full_name:'Same Name',phone_number:'09123456789',intake_status:'under_verification',created_at:'2026-10-01T00:00:00Z',updated_at:'2026-10-02T00:00:00Z'});
const page=(items=[],next_cursor=null)=>({items,next_cursor,has_more:next_cursor!==null,as_of:'2026-10-04T00:00:00Z'});
const apps=(items=[],next_cursor=null)=>({...page(items,next_cursor),intake:{applicant_id:id,intake_reference:'INT/A',client_id:client,intake_status:'eligible_for_cif'}});
const saved=(reference='APP/A')=>({application_id:app,application_reference:reference,client_id:client,created_at:'2026-10-01T00:00:00Z',application_version_id:version,version_number:2,recorded_at:'2026-10-02T00:00:00Z'});
const flush=async()=>{await setImmediate();await setImmediate();};
const disposers=[];
afterEach(()=>{for(const dispose of disposers.splice(0))dispose();});
function mount(read=()=>page([row()]),options={}){const root=new Element(),calls=[],session={user:{id:'staff',role:'employee'},permissions:['client_onboarding.requirement.review']};const handle=mountOfficeApplicationFinder({root,api:{request:async(path)=>{calls.push(path);return read(path);}},getSession:()=>session,...options});disposers.push(handle);return {root,calls,handle,session};}
function search(root,q,status=''){root.querySelector('[name="q"]').value=q;root.querySelector('[name="status"]').value=status;fire(root.querySelector('[data-finder-search]'),'submit');}
test('authorized entry automatically loads recent rows, truthful fields, status, private markers and duplicate identity controls',async()=>{const {root,calls}=mount(()=>page([row(),{...row('INT/B'),applicant_id:client}]));await flush();assert.equal(calls.length,1);assert.match(calls[0],/applicants\?limit=25$/);assert.match(root.textContent,/Recent office intakes.*Newest intakes first/);for(const value of ['Same Name','09123456789','INT/A','INT/B','Under verification','2026'])assert.ok(root.textContent.includes(value));assert.equal(root.querySelectorAll('[data-choose-intake]').length,2);assert.ok(root.querySelector('[data-finder-results]').getAttribute('data-private-panel')!==null);});
test('loading, empty recent, no matches, malformed and not found are independent read states',async()=>{let resolve;const {root,handle}=mount(()=>new Promise(r=>resolve=r));assert.match(root.textContent,/Loading recent office intakes/);resolve(page());await flush();assert.match(root.textContent,/No saved office intakes/);search(root,'Alice');await flush();resolve(page());await flush();assert.match(root.textContent,/No matching office intakes/);const bad=mount(()=>({items:[]}));await flush();assert.match(bad.root.textContent,/could not be verified/);const missing=mount(()=>{throw Object.assign(new Error('server private text'),{status:404});});await flush();assert.match(missing.root.textContent,/not found/i);assert.doesNotMatch(missing.root.textContent,/server private text/);handle();});
test('server paging preserves prior authorized rows on failure, filter changes reset cursor, and no total is inferred',async()=>{let fail=false;const {root,calls}=mount(path=>{if(path.includes('cursor=')){if(fail)throw new Error('offline');return page([row('INT/B')]);}return page([row()],'opaque/one');});await flush();fire(root.querySelector('[data-finder-next]'),'click');await flush();assert.match(calls.at(-1),/cursor=opaque%2Fone/);assert.match(root.textContent,/INT\/B/);search(root,'  Alice  ','eligible_for_cif');await flush();assert.match(calls.at(-1),/q=Alice.*status=eligible_for_cif/);assert.doesNotMatch(calls.at(-1),/cursor=/);fail=true;fire(root.querySelector('[data-finder-next]'),'click');await flush();assert.match(root.textContent,/INT\/A/);assert.match(root.textContent,/incomplete.*read failed/i);assert.doesNotMatch(root.textContent,/total|of 1/i);});
test('short or oversized queries do not read; normalized new search supersedes older response',async()=>{const pending=[];const {root,calls}=mount(path=>new Promise(resolve=>pending.push({path,resolve})));pending[0].resolve(page());await flush();search(root,'ab');await flush();assert.equal(calls.length,1);search(root,'x'.repeat(201));await flush();assert.equal(calls.length,1);search(root,' Old ');await flush();search(root,' New ');await flush();pending[2].resolve(page([row('NEW')]));await flush();pending[1].resolve(page([row('OLD')]));await flush();assert.match(root.textContent,/NEW/);assert.doesNotMatch(root.textContent,/OLD/);});
test('explicit application list uses verified context, paginates and hands off exact identity/version without draft or automatic selection',async()=>{const chosen=[];const {root,handle,calls}=mount(path=>path.includes('/applications')?apps([saved(),{...saved('APP/B'),application_id:id,application_version_id:null,version_number:null,recorded_at:null}],'app-next'):page([row()]),{onChooseApplication:value=>{chosen.push(value);return false;}});await flush();handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client,applicationReference:'DRAFT/UNSAVED',applicationSaved:false});await flush();assert.equal(chosen.length,0);assert.match(calls.at(-1),/INT%2FA\/applications\?limit=25$/);assert.match(root.textContent,/Applications for this client.*APP\/A.*Saved version 2.*APP\/B.*No saved version/);assert.doesNotMatch(root.textContent,/DRAFT/);assert.ok(root.querySelector('[data-application-results]').getAttribute('data-private-panel')!==null);fire(root.querySelector('[data-choose-application]'),'click');await flush();assert.deepEqual(chosen[0],{intakeReference:'INT/A',clientId:client,applicationReference:'APP/A',applicationId:app,applicationVersionId:version,versionNumber:2});assert.match(root.textContent,/existing work.*kept|not opened/i);assert.ok(root.querySelector('[data-choose-application]').focused);fire(root.querySelector('[data-applications-next]'),'click');await flush();assert.match(calls.at(-1),/cursor=app-next/);});
test('Change case retains query/page and focus; Clear search is independent of selected case',async()=>{let chosen=0;const {root,handle}=mount(path=>path.includes('cursor=')?page([row('INT/B')]):page([row()],'next'),{onChooseCase:()=>{chosen++;return true;}});await flush();search(root,'Alice');await flush();fire(root.querySelector('[data-finder-next]'),'click');await flush();fire(root.querySelector('[data-choose-intake]'),'click');await flush();handle.setContext({mode:'saved-case',intakeReference:'INT/B',clientId:null});handle.showFinder();assert.equal(root.querySelector('[name="q"]').value,'Alice');assert.match(root.textContent,/INT\/B/);assert.ok(root.querySelector('[data-choose-intake]').focused);fire(root.querySelector('[data-finder-clear]'),'click');await flush();assert.equal(chosen,1);assert.equal(root.querySelector('[name="q"]').value,'');});
test('revoked access between pages clears both private panels; disposal and owner change silence stale reads',async()=>{let deny=false,denied=0;const {root,handle,session}=mount(path=>{if(deny)throw Object.assign(new Error('private'),{status:403});return path.includes('/applications')?apps([saved()]):page([row()],'next');},{onDenied:()=>denied++});await flush();handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client});await flush();handle.showFinder();deny=true;fire(root.querySelector('[data-finder-next]'),'click');await flush();assert.equal(denied,1);assert.doesNotMatch(root.textContent,/Same Name|APP\/A|INT\/A/);const other=mount();await flush();other.session.permissions=[];await other.handle.refreshReadOnly();assert.doesNotMatch(other.root.textContent,/Same Name/);handle();session.user.id='other';});
test('saved application paging restores keyboard focus without stealing moved focus and keeps authorized rows on a later failure',async()=>{let resolve,fail=false;const {root,handle}=mount(path=>path.includes('/applications')?(path.includes('cursor=')?new Promise(r=>resolve=r):apps([saved()],'next')):page([row()]));await flush();handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client});await flush();fire(root.querySelector('[data-applications-next]'),'click');resolve(apps([{...saved('APP/B'),application_id:id}],'third'));await flush();assert.equal(root.querySelector('[data-application-results]').querySelector('[data-page-heading]').focused,true);fire(root.querySelector('[data-applications-next]'),'click');const elsewhere=root.querySelector('[name="q"]');elsewhere.focus();root.ownerDocument.dispatchEvent(new Event('focusin'));resolve(apps([saved('APP/C')]));await flush();assert.equal(root.querySelector('[data-application-results]').querySelector('[data-page-heading]').focused,undefined);assert.equal(elsewhere.focused,true);const other=mount(path=>{if(path.includes('/applications')){if(fail)throw Error('private offline text');return apps([saved()],'next');}return page([row()]);});await flush();other.handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client});await flush();fail=true;fire(other.root.querySelector('[data-applications-next]'),'click');await flush();assert.match(other.root.querySelector('[data-application-results]').textContent,/incomplete.*read failed.*APP\/A/i);assert.doesNotMatch(other.root.textContent,/private offline text/);});
test('application context and partial version triples are rejected instead of displayed',async()=>{for(const value of [{...apps([saved()]),intake:{...apps().intake,client_id:id}},apps([{...saved(),version_number:null}]),apps([{...saved(),application_version_id:null,version_number:null}]),apps([saved(),saved()]),{...page([row()]),has_more:true}]){const {root,handle}=mount(path=>path.includes('/applications')?value:page([row()]));await flush();handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client});await flush();assert.match(root.querySelector('[data-application-results]').textContent,/could not be verified/);assert.equal(root.querySelectorAll('[data-choose-application]').length,0);}});
test('an unpromoted intake has no application read; empty applications and denied later pages stay distinct',async()=>{let denied=false;const {root,handle,calls}=mount(path=>{if(path.includes('/applications')){if(denied)throw Object.assign(Error('denied'),{status:401});return apps([],'next');}return page([row()]);});await flush();handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:null});await flush();assert.equal(calls.length,1);handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client});await flush();assert.match(root.textContent,/No saved applications for this client/);denied=true;fire(root.querySelector('[data-applications-next]'),'click');await flush();assert.match(root.textContent,/access is unavailable/);assert.doesNotMatch(root.textContent,/Same Name|APP\/A|INT\/A/);});
test('disposed or replaced-owner mounts do not publish an outstanding private read',async()=>{for(const change of ['dispose','owner','abort']){let resolve;const controller=new AbortController(),h=mount(()=>new Promise(r=>resolve=r),{signal:controller.signal});if(change==='dispose')h.handle();else if(change==='owner')h.session.user.id='different';else controller.abort();resolve(page([row()]));await flush();assert.doesNotMatch(h.root.textContent,/Same Name|INT\/A/);assert.equal(h.root.querySelectorAll('[data-choose-intake]').length,0);}});
test('inherited object keys are invalid intake states in both projections',async()=>{for(const intake_status of ['constructor','toString']){const recent=mount(()=>page([{...row(),intake_status}]));await flush();assert.match(recent.root.textContent,/could not be verified/);assert.equal(recent.root.querySelectorAll('[data-choose-intake]').length,0);const application=mount(path=>path.includes('/applications')?{...apps([saved()]),intake:{...apps().intake,intake_status}}:page([row()]));await flush();application.handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client});await flush();assert.match(application.root.querySelector('[data-application-results]').textContent,/could not be verified/);assert.equal(application.root.querySelectorAll('[data-choose-application]').length,0);}});
test('stored authority or device changes clear private pages with a stale context session before another read',async()=>{for(const loss of ['authority','device']){const session={user:{id:'staff',role:'employee'},permissions:['client_onboarding.requirement.review']};let stored=session,device='original',reads=0,denials=0;const h=mount(()=>page(),{getSession:()=>session,onDenied:()=>denials++,api:{sessionStore:{load:()=>stored,deviceId:()=>device},request:async path=>{reads++;return path.includes('/applications')?apps([saved()]):page([row()]);}}});await flush();h.handle.setContext({mode:'saved-case',intakeReference:'INT/A',clientId:client});await flush();const before=reads;if(loss==='authority')stored={...stored,permissions:[]};else device='replacement';await h.handle.refreshReadOnly();assert.equal(reads,before);assert.equal(denials,1);assert.doesNotMatch(h.root.textContent,/Same Name|INT\/A|APP\/A/);}});
