import assert from 'node:assert/strict';
import test from 'node:test';
import {setImmediate} from 'node:timers/promises';
import {Element,fire} from './helpers/dom.mjs';
import {mountEmployeeWorkspace} from '../assets/employee-workspace.js';
import {mountManagementWorkspace} from '../assets/roles/management.js';
const CLIENT='11111111-1111-4111-8111-111111111111',APPLICANT='22222222-2222-4222-8222-222222222222',APP='33333333-3333-4333-8333-333333333333',VERSION='44444444-4444-4444-8444-444444444444',CIF='55555555-5555-4555-8555-555555555555';
const flush=async()=>{await setImmediate();await setImmediate();};
const page=items=>({items,next_cursor:null,has_more:false,as_of:'2026-10-04T00:00:00Z'});
const row=ref=>({applicant_id:ref==='INT/A'?APPLICANT:CIF,intake_reference:ref,client_id:CLIENT,full_name:'Synthetic duplicate name',phone_number:'09123456789',intake_status:'eligible_for_cif',created_at:'2026-10-01T00:00:00Z',updated_at:'2026-10-02T00:00:00Z'});
const record=ref=>({applicant_id:ref==='INT/A'?APPLICANT:CIF,application_reference:ref,status:'eligible_for_cif',client_id:CLIENT,full_name:'Synthetic duplicate name',phone_number:'09123456789',email:null,present_address:'Synthetic office address',privacy_consent:true,accuracy_declaration:true,bypassed_requirements:[],bypass_reason:null,requirements:Object.fromEntries(['national_id','tin_id','meralco_bill','collector_visit'].map(name=>[name,{status:'pending',evidence_reference:null,note:null}]))});
const saved=(reference,number=2)=>({client_id:CLIENT,application_id:APP,application_version_id:VERSION,application_reference:reference,cif_version_id:CIF,cif_version_number:1,version_number:number,recorded_at:'2026-10-03T00:00:00Z',review_scope:'loan_application_information_only',requested_loan_type_name:null,missing_fields:[],information:{request:{requested_loan_type_id:null,purpose:'Synthetic purpose',requested_amount:null,requested_payment_arrangement:null,requested_term:null,preferred_first_payment_date:null},repayment:{repayment_source:null,source_details:null,monthly_gross_income:null,monthly_net_income:null,has_existing_obligations:false,obligations:[]}}});
async function harness(role,enter=true){const h={root:new Element(),calls:[],controller:new AbortController(),accept:false,fail:false,denyList:false,denyStage:false,version:2};h.root.dataset={};h.context={root:h.root,session:{user:{id:CLIENT,role,roles:[role]},permissions:['client_onboarding.requirement.review']},confirmDiscard:()=>h.accept,signal:h.controller.signal,setNavigation(){},activateNavigation(){},registerWorkspaceHandle:handle=>h.handle=handle,api:{async request(path,options={}){h.calls.push({path,options});if(path.startsWith('/api/v1/management/onboarding/applicants?')){if(h.denyList)throw Object.assign(Error('synthetic denied'),{status:403});return page([row('INT/A'),row('INT/B')]);}if(path.endsWith('/applications?limit=25'))return {...page(['APP/A','APP/B'].map((ref,index)=>({application_id:index?CIF:APP,application_reference:ref,client_id:CLIENT,created_at:'2026-10-02T00:00:00Z',application_version_id:h.versionless?null:VERSION,version_number:h.versionless?null:2,recorded_at:h.versionless?null:'2026-10-03T00:00:00Z'}))),intake:{applicant_id:APPLICANT,intake_reference:'INT/A',client_id:CLIENT,intake_status:'eligible_for_cif'}};if(path.endsWith('/case')){if(h.denyStage)throw Object.assign(Error('denied'),{status:403});if(h.fail&&path.includes('INT%2FB'))throw Error('offline');return record(path.includes('INT%2FB')?'INT/B':'INT/A');}if(path.endsWith('/cif-client'))return {client_id:CLIENT,application_reference:'INT/A'};if(path.includes('/loan-applications/')&&path.endsWith('/review-summary'))return saved(path.includes('APP%2FB')?'APP/B':'APP/A',h.version);if(path.endsWith('/entry-context'))return {client_id:CLIENT,cif_version_id:CIF,cif_version_number:1,loan_types:[]};if(path==='/api/v1/account')return {profile:{full_name:'Synthetic staff'},devices:[]};if(path.includes('activity-notifications'))return [];return {};}}};await (role==='management'?mountManagementWorkspace:mountEmployeeWorkspace)(h.context);h.entry=async()=>{if(role==='management')await h.handle.activate('management-clients-loans','management-office');else h.handle.activate('employee-onboarding');await flush();};h.open=async index=>{fire(h.root.querySelectorAll('[data-choose-intake]')[index],'click');await flush();};if(enter)await h.entry();return h;}
for(const role of ['management','employee']){
 test(`${role} Office entry loads recent list only on entry and chooses duplicate names by exact protected reference`,async t=>{const h=await harness(role);t.after(()=>h.controller.abort());assert.equal(h.calls.filter(c=>c.path.startsWith('/api/v1/management/onboarding/applicants?')).length,1);assert.ok(h.root.querySelector('[data-office-finder]'));assert.equal(h.root.querySelectorAll('[data-choose-intake]').length,2);await h.open(1);assert.ok(h.calls.some(c=>c.path.endsWith('/INT%2FB/case')));assert.match(h.root.querySelector('[data-office-onboarding]').textContent,/INT\/B/);});
 test(`${role} cancelled dirty replacement and failed revalidation preserve actual intake controls; finder Refresh remains read-only`,async t=>{const h=await harness(role);t.after(()=>h.controller.abort());await h.open(0);const intake=h.root.querySelector('[data-office-onboarding]');fire(intake.querySelector('[data-new-intake]'),'click');await flush();const field=intake.querySelector('[name="full_name"]');field.value='Unfinished office form';fire(field,'input');fire(h.root.querySelector('[data-finder-change]'),'click');await h.open(1);assert.ok(intake.querySelector('[name="full_name"]')===field,'cancelled keeps owner');h.fail=true;h.accept=true;await h.open(1);assert.ok(intake.querySelector('[name="full_name"]')===field,'failed read keeps owner');const before=h.calls.length;await h.handle.refreshVisible();await flush();assert.equal(h.calls.length,before+1);assert.ok(h.calls.at(-1).path.startsWith('/api/v1/management/onboarding/applicants?'));assert.ok(intake.querySelector('[name="full_name"]')===field);assert.equal(h.calls.filter(c=>c.options.method).length,0);});
 test(`${role} saved application choice verifies exact version and never adopts a changed or versionless row`,async t=>{const h=await harness(role);t.after(()=>h.controller.abort());await h.open(0);assert.equal(h.root.querySelectorAll('[data-choose-application]').length,2);assert.equal(h.calls.filter(c=>c.path.includes('/loan-applications/')).length,0);h.version=3;fire(h.root.querySelector('[data-choose-application]'),'click');await flush();assert.match(h.root.querySelector('[data-application-results]').textContent,/not opened/);assert.match(h.root.querySelector('[data-office-application-review]').textContent,/version changed/);h.version=2;fire(h.root.querySelector('[data-choose-application]'),'click');await flush();assert.match(h.root.querySelector('[data-office-application-review]').textContent,/Saved application|version 2/i);h.versionless=true;fire(h.root.querySelector('[data-applications-refresh]'),'click');await flush();assert.match(h.root.querySelector('[data-application-results]').textContent,/No saved version/);fire(h.root.querySelector('[data-choose-application]'),'click');await flush();assert.match(h.root.querySelector('[data-application-results]').textContent,/not opened/);assert.match(h.root.querySelector('[data-office-application-review]').textContent,/version 2/i);});
 test(`${role} list denial clears every mounted Office stage and stage denial clears hidden finder data`,async t=>{const h=await harness(role);t.after(()=>h.controller.abort());await h.open(0);h.denyList=true;fire(h.root.querySelector('[data-finder-change]'),'click');await h.handle.refreshVisible();await flush();assert.equal(h.root.querySelector('[data-office-onboarding]').querySelector('[name="applicationReference"]'),null);assert.doesNotMatch(h.root.querySelector('[data-office-finder]').textContent,/Synthetic duplicate|INT\/A|APP\/A/);const other=await harness(role);t.after(()=>other.controller.abort());await other.open(0);other.denyStage=true;await other.handle.refreshVisible();await flush();assert.doesNotMatch(other.root.querySelector('[data-office-finder]').textContent,/Synthetic duplicate|INT\/A|APP\/A/);});
}
test('Employee can open a later stage directly and return to the authorized recent list without implicit selection',async t=>{const h=await harness('employee',false);t.after(()=>h.controller.abort());h.handle.activate('employee-application-review');await flush();assert.ok(h.root.querySelector('[data-office-application-review]').querySelector('[name="intakeReference"]'));assert.equal(h.calls.filter(c=>c.path.startsWith('/api/v1/management/onboarding/applicants?')).length,0);fire(h.root.querySelector('#employee-application-review').querySelector('[data-office-change-case]'),'click');await flush();assert.equal(h.root.querySelectorAll('[data-choose-intake]').length,2);assert.equal(h.calls.filter(c=>c.path.endsWith('/case')).length,0);});
