import assert from 'node:assert/strict';
import test from 'node:test';
import { File } from 'node:buffer';
import { setImmediate } from 'node:timers/promises';
import { Element, fire } from './helpers/dom.mjs';
import { createOfficeCaseContext } from '../assets/office-case-context.js';
import { mountOfficeCifSelection } from '../assets/office-cif-selection.js';
import { mountOfficeOnboarding } from '../assets/office-onboarding.js';

const client='11111111-1111-4111-8111-111111111111', version='22222222-2222-4222-8222-222222222222';
const session={user:{id:'office',role:'employee'},permissions:['client_onboarding.requirement.review'],access_token:'synthetic'};
const summary={client_id:client,cif_version_id:version,version_number:1,status:'draft',review_scope:'cif_information_only',full_name:'Synthetic applicant',phone_number:'09171111111',email:null,present_address:'Synthetic address',can_correct_information:true};
const pending=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
function harness(confirmDiscard=()=>false){
 const root=new Element(), calls=[]; let currentSession=session;
 const h={root,calls,read:async path=>path.includes('/cif-client')?{application_reference:decodeURIComponent(path.split('/').at(-2)),client_id:client}:path.includes('review-summary')?summary:path.includes('/privacy/context')?{client_id:client,cif_version_id:version,subject_id:version,application_id:null,application_version_id:null,purpose:'privacy_acknowledgment',issuable:true,detail:'Synthetic privacy',snapshot_sha256:'a'.repeat(64),review_snapshot:{schema_version:1,scope:'privacy_acknowledgment',client_id:client,cif_version_id:version,optional_service_communications:false,notice:{version:'v1',sha256:'b'.repeat(64)},consent:{version:'v1',sha256:'c'.repeat(64)}}}:{client_id:client,cif_version_id:version,purpose:'cif_review',snapshot_sha256:'a'.repeat(64)}};
 h.coordinator=createOfficeCaseContext({getSession:()=>currentSession,confirmDiscard});
 h.dispose=mountOfficeCifSelection({root,session,getSession:()=>currentSession,confirmDiscard,api:{request(path,options={}){calls.push({path,options});return h.read(path,options);}},officeCaseContext:h.coordinator,registerHandle:handle=>{h.handle=handle;h.coordinator.registerStage('cif',handle);}});
 h.logout=()=>{currentSession=null;h.coordinator.getContext();};return h;
}
const input=h=>h.root.querySelector('[name="applicationReference"]');
async function open(h,reference='INTAKE-A'){input(h).value=reference;fire(input(h),'input');fire(h.root.querySelector('form'),'submit');await setImmediate();}
async function files(h){await open(h);fire(h.root.querySelector('[data-open-cif-workflow]'),'click');await setImmediate();const signed=h.root.querySelector('[name="signedScan"]'),privacy=h.root.querySelector('[name="signedPrivacyScan"]'); const a=new File(['scan'],'signed.pdf',{type:'application/pdf'}),b=new File(['privacy'],'privacy.pdf',{type:'application/pdf'});signed.files=[a];privacy.files=[b];fire(signed,'change');fire(privacy,'change');const witness=h.root.querySelector('[name="witnessedPrivacySignature"]');witness.checked=true;fire(witness,'change');return {signed,privacy,a,b,witness};}
function retained(h,f){assert.equal(h.root.querySelector('[name="signedScan"]'),f.signed);assert.equal(f.signed.files[0],f.a);assert.equal(h.root.querySelector('[name="signedPrivacyScan"]'),f.privacy);assert.equal(f.privacy.files[0],f.b);assert.equal(f.witness.checked,true);assert.equal(h.coordinator.getContext().intakeReference,'INTAKE-A');assert.equal(h.calls.filter(c=>c.options.method && c.options.method!=='GET').length,0);}
for(const event of ['input','change','clear'])test(`CIF ${event} preserves actual signed/privacy Files and live controls`,async()=>{const h=harness(),f=await files(h);if(event==='clear')fire(h.root.querySelector('[data-clear-cif-search]'),'click');else{input(h).value='OTHER';fire(input(h),event);}retained(h,f);assert.equal(h.handle.isDirty(),true);h.dispose();});
for(const failure of [404,500,'network'])test(`CIF candidate ${failure} preserves authorized File draft`,async()=>{const h=harness(),f=await files(h);h.read=async()=>{throw Object.assign(new Error('Synthetic unavailable'),{status:failure});};await open(h,'INTAKE-B');retained(h,f);assert.match(h.root.textContent,/unavailable/i);h.dispose();});
test('CIF failed candidate summary preserves old authorized draft before consent',async()=>{let consent=0;const h=harness(()=>{consent++;return true;}),f=await files(h);const read=h.read;h.read=path=>path.includes('review-summary')?Promise.reject(Error('Summary unavailable')):read(path);await open(h,'INTAKE-B');retained(h,f);assert.equal(consent,0);h.dispose();});
test('CIF cancel Open and Close keeps Files and initiating control focus',async()=>{let consent=0;const h=harness(()=>{consent++;return false;}),f=await files(h);await open(h,'INTAKE-B');retained(h,f);assert.equal(h.root.querySelector('button[type="submit"]').focused,true);const close=h.root.querySelector('[data-close-cif-case]');fire(close,'click');await setImmediate();retained(h,f);assert.equal(close.focused,true);assert.equal(consent,2);h.dispose();});
for(const during of ['read','consent'])test(`CIF edits while ${during} pending revoke earlier replacement`,async()=>{const hold=pending();const h=harness(during==='consent'?()=>hold.promise:()=>true),f=await files(h);const read=h.read;if(during==='read')h.read=path=>path.includes('/cif-client')?hold.promise:read(path);input(h).value='INTAKE-B';fire(h.root.querySelector('form'),'submit');await setImmediate();const field=h.root.querySelector('[name="providerReference"]');field.value='Later edit';fire(field,'input');hold.resolve(during==='read'?{application_reference:'INTAKE-B',client_id:client}:true);await setImmediate();retained(h,f);assert.equal(field.value,'Later edit');h.dispose();});
test('same-case Back/Next and Open retain CIF children and zero writes',async()=>{const h=harness(()=>true),f=await files(h);await h.coordinator.requestTransition({kind:'navigate',targetStage:'application'});await h.coordinator.requestTransition({kind:'navigate',targetStage:'cif'});await open(h);retained(h,f);h.dispose();});
test('new_intake_detaches_all_old_stage_handoffs and disposes real CIF Files',async()=>{const h=harness(()=>true),f=await files(h);h.coordinator.acceptVerifiedContext({applicationReference:'APP-A',applicationId:version,applicationVersionId:client,applicationSaved:true},h.coordinator.getGeneration());assert.equal(await h.coordinator.requestTransition({kind:'new-intake',targetStage:'intake'}),true);const c=h.coordinator.getContext();for(const key of ['intakeReference','clientId','applicationReference','applicationId','applicationVersionId'])assert.equal(c[key],null);assert.equal(input(h).value,'');assert.equal(h.root.querySelector('[name="signedScan"]'),null);assert.equal(f.signed.value,'');assert.equal(f.witness.checked,false);h.dispose();});
for(const event of ['logout','denial'])test(`CIF late response after ${event} cannot restore private Files`,async()=>{const h=harness(()=>true),f=await files(h),hold=pending();h.read=()=>hold.promise;input(h).value='INTAKE-B';fire(h.root.querySelector('form'),'submit');await setImmediate();if(event==='logout'){h.logout();hold.resolve({application_reference:'INTAKE-B',client_id:client});}else hold.reject(Object.assign(Error('Denied'),{status:403}));await setImmediate();assert.equal(h.root.querySelector('[name="signedScan"]'),null);assert.equal(f.signed.value,'');assert.equal(f.witness.checked,false);assert.equal(h.coordinator.getContext().intakeReference,null);});
test('CIF correction entry cannot silently destroy selected signed Files',async()=>{const h=harness(),f=await files(h);fire(h.root.querySelector('[data-correct-cif]'),'click');await setImmediate();retained(h,f);assert.equal(h.root.querySelector('[name="reason"]'),null);h.dispose();});
test('CIF correction text participates in replacement dirty tracking',async()=>{const h=harness();await open(h);fire(h.root.querySelector('[data-correct-cif]'),'click');await setImmediate();const reason=h.root.querySelector('[name="reason"]');reason.value='Unfinished correction';fire(reason,'input');await open(h,'INTAKE-B');assert.equal(h.root.querySelector('[name="reason"]'),reason);assert.equal(h.coordinator.getContext().intakeReference,'INTAKE-A');h.dispose();});
test('intake-initiated New detaches its identity and registered CIF owner without writes',async()=>{const h=harness(()=>true),f=await files(h),intake=new Element();const dispose=mountOfficeOnboarding({root:intake,api:{request(){throw Error('Navigation must not read');}},session,officeCaseContext:h.coordinator,registerHandle:handle=>h.coordinator.registerStage('intake',handle)});fire(intake.querySelector('[data-new-intake]'),'click');await setImmediate();assert.equal(h.coordinator.getContext().mode,'new-intake');assert.equal(input(h).value,'');assert.equal(h.root.querySelector('[name="signedScan"]'),null);assert.equal(f.witness.checked,false);assert.ok(intake.querySelector('[data-intake-form]'));assert.equal(h.calls.filter(c=>c.options.method).length,0);dispose();h.dispose();});
test('CIF correction approved discard clears old exact-version Files deliberately',async()=>{let text;const h=harness(message=>{text=message;return true;}),f=await files(h);fire(h.root.querySelector('[data-correct-cif]'),'click');await setImmediate();assert.equal(text,'You have unsaved changes. Keep editing or discard changes?');assert.equal(h.root.querySelector('[name="signedScan"]'),null);assert.equal(f.witness.checked,false);assert.ok(h.root.querySelector('[name="reason"]'));h.dispose();});
test('newer CIF child edits invalidate correction-entry discard consent',async()=>{const hold=pending(),h=harness(()=>hold.promise),f=await files(h);const button=h.root.querySelector('[data-correct-cif]');fire(button,'click');await setImmediate();f.witness.checked=false;fire(f.witness,'change');hold.resolve(true);await setImmediate();assert.equal(h.root.querySelector('[name="signedScan"]'),f.signed);assert.equal(f.privacy.files[0],f.b);assert.equal(button.focused,true);assert.equal(h.root.querySelector('[name="reason"]'),null);h.dispose();});
test('lookup edits keep callbacks attached to the authorized CIF owner',async()=>{const h=harness();await open(h);input(h).value='OTHER';fire(input(h),'input');fire(h.root.querySelector('[data-correct-cif]'),'click');await setImmediate();assert.ok(h.root.querySelector('[name="reason"]'));const read=h.read;h.read=async path=>path.includes('include_correction')?Promise.reject(Object.assign(Error('Denied'),{status:403})):read(path);fire(h.root.querySelector('[data-cancel-cif]'),'click');await setImmediate();fire(h.root.querySelector('[data-correct-cif]'),'click');await setImmediate();assert.equal(h.root.querySelector('[name="reason"]'),null);assert.equal(h.coordinator.getContext().intakeReference,null);h.dispose();});
test('pending and uncertain signed evidence retain File and exact retry identity',async()=>{const h=harness(()=>true),f=await files(h),hold=pending();const read=h.read;h.read=(path,options)=>options.method==='POST'?hold.promise:read(path);h.root.querySelector('[name="witnessed"]').checked=true;fire(h.root.querySelector('[data-signed-cif]').querySelector('form'),'submit');await setImmediate();assert.equal(h.handle.isWritePending(),true);assert.equal(await h.coordinator.requestTransition({kind:'new-intake'}),false);assert.equal(h.handle.resetCase(),false);hold.reject(Error('Response lost'));await setImmediate();assert.equal(h.handle.isWritePending(),false);assert.equal(h.handle.isUncertain(),true);assert.equal(await h.coordinator.requestTransition({kind:'close'}),false);assert.equal(f.signed.files[0],f.a);const first=h.calls.find(c=>c.options.method==='POST');h.read=async(path,options)=>{if(options.method==='POST')throw Error('Still lost');return read(path);};fire(h.root.querySelector('[data-signed-cif]').querySelector('form'),'submit');await setImmediate();const writes=h.calls.filter(c=>c.options.method==='POST');assert.equal(writes.length,2);assert.equal(writes[1].path,first.path);assert.equal(writes[1].options.rawBody,f.a);h.dispose();assert.equal(f.witness.checked,false);});
test('pending and uncertain correction keep original operation and block Cancel/replacement',async()=>{const h=harness(()=>true);await open(h);fire(h.root.querySelector('[data-correct-cif]'),'click');await setImmediate();const reason=h.root.querySelector('[name="reason"]');reason.value='Synthetic correction';const hold=pending(),read=h.read;h.read=(path,options)=>options.method==='PATCH'?hold.promise:read(path);fire(h.root.querySelector('[data-office-cif-correction]').querySelector('form'),'submit');await setImmediate();assert.equal(h.handle.isWritePending(),true);fire(h.root.querySelector('[data-cancel-cif]'),'click');assert.equal(h.root.querySelector('[name="reason"]'),reason);assert.equal(await h.coordinator.requestTransition({kind:'close'}),false);hold.reject(Error('Save response lost'));await setImmediate();assert.equal(h.handle.isUncertain(),true);fire(h.root.querySelector('[data-cancel-cif]'),'click');assert.equal(h.root.querySelector('[name="reason"]'),reason);assert.equal(await h.coordinator.requestTransition({kind:'new-intake'}),false);assert.equal(h.calls.filter(c=>c.options.method==='PATCH').length,1);h.dispose();});
test('acknowledged CIF correction with failed reload retains known identity and read-only recovery',async()=>{const h=harness();await open(h);fire(h.root.querySelector('[data-correct-cif]'),'click');await setImmediate();h.root.querySelector('[name="reason"]').value='Synthetic correction';const read=h.read;h.read=(path,options)=>options.method==='PATCH'?Promise.resolve(summary):path.endsWith('review-summary')?Promise.reject(Error('Reload unavailable')):read(path);fire(h.root.querySelector('[data-office-cif-correction]').querySelector('form'),'submit');await setImmediate();assert.equal(h.coordinator.getContext().intakeReference,'INTAKE-A');assert.equal(h.coordinator.getContext().clientId,client);assert.match(h.root.textContent,/correction saved.*details.*unavailable/i);const reload=h.root.querySelector('[data-reload-saved-cif]');assert.ok(reload);h.read=read;fire(reload,'click');await setImmediate();assert.ok(h.root.querySelector('[data-open-cif-workflow]'));assert.equal(h.calls.filter(c=>c.options.method==='PATCH').length,1);h.dispose();});
test('privacy upload pending and uncertain states participate in CIF case-change guards',async()=>{const h=harness(()=>true),f=await files(h),hold=pending(),read=h.read;h.read=(path,options)=>options.method==='POST'?hold.promise:read(path);fire(h.root.querySelector('[data-privacy-confirm]'),'submit');await setImmediate();assert.equal(h.handle.isWritePending(),true);assert.equal(await h.coordinator.requestTransition({kind:'new-intake'}),false);hold.reject(Error('Privacy response lost'));await setImmediate();assert.equal(h.handle.isWritePending(),false);assert.equal(h.handle.isUncertain(),true);assert.equal(await h.coordinator.requestTransition({kind:'close'}),false);assert.equal(h.root.querySelector('[name="signedPrivacyScan"]'),f.privacy);assert.equal(f.privacy.files[0],f.b);assert.equal(h.calls.filter(c=>c.options.method==='POST').length,1);h.dispose();assert.equal(f.witness.checked,false);});
