import test from 'node:test';import assert from 'node:assert/strict';import {Element,fire} from './helpers/dom.mjs';
const module=await import('../assets/treasury-workspace.js').catch(()=>({}));
const account='10000000-0000-4000-8000-000000000001',context='20000000-0000-4000-8000-000000000001';
const actions=['account_configure','account_grant','opening_prepare','opening_activate','claim_review','receipt_verify','receipt_apply','disbursement_record','transfer_record','movement_classify','movement_correct','receipt_application_reverse','reconciliation_observe','reconciliation_match','reconciliation_close','reconciliation_supersede'];
const session={user:{id:context,role:'management',status:'active'},device_id:'installation',device_registered:true,permissions:['treasury.view']};
const workspace={contract_version:1,actor:{user_id:context,device_id:account},enabled:true,owner_configured:true,blockers:[],capabilities:Object.fromEntries([...actions,'evidence_upload'].map(action=>[action,true])),claims:[],accounts:[{id:account,ledger_context_id:context,context:'synthetic',kind:'gcash',currency:'PHP',alias:'Synthetic actual wallet',ownership:'synthetic',version:1,actions:[...actions,'evidence_upload'],balance:{available:true,opening_id:context,cutoff:'2026-10-02T00:00:00Z',expected_balance:'90071992547409.93',movement_watermark:3,last_verified_at:'2026-10-02T00:00:00Z'}}]};
const empty={items:[],total_count:0,limit:50,offset:0,has_more:false,totals:null};
test('account snapshot shows exact server cash with cutoff and missing opening remains unavailable',()=>{assert.equal(typeof module.renderTreasuryAccounts,'function');const html=module.renderTreasuryAccounts(workspace);assert.match(html,/90,071,992,547,409.93/);assert.match(html,/synthetic|Synthetic/);assert.match(html,/cutoff|Cutoff/);const missing=module.renderTreasuryAccounts({...workspace,accounts:[{...workspace.accounts[0],balance:{available:false,expected_balance:null}}]});assert.match(missing,/Opening position not supplied/);assert.doesNotMatch(missing,/₱0.00/);});
test('received, blocked application, unconfirmed debit and draft approvals remain distinct',()=>{assert.equal(typeof module.treasuryOutcomeMessage,'function');assert.match(module.treasuryOutcomeMessage({status:'saved',action:'receipt_verify',result:{receipt:{status:'received_awaiting_recording'}}}),/received|recording/i);assert.match(module.treasuryOutcomeMessage({status:'saved',action:'disbursement_record',result:{event:{status:'debited_destination_unconfirmed'},source_link:{status:'blocked',blocker:'Source signing required'}}}),/destination|Source signing/);assert.doesNotMatch(module.treasuryOutcomeMessage({status:'blocked',action:'receipt_apply',result:{message:'Stale allocation'}}),/payment recorded/i);});
test('paged totals are complete server values, never sums of loaded cards',()=>{assert.equal(typeof module.renderTreasuryPage,'function');const html=module.renderTreasuryPage('receipts',{items:[{id:account,amount:'1.00',applied_amount:'0.00'}],total_count:200,offset:0,limit:50,has_more:true,totals:{unapplied_amount:'90071992547409.93',applied_amount:'300.00',refunded_amount:'0.00'}});assert.match(html,/200/);assert.match(html,/90,071,992,547,409.93/);assert.match(html,/server|Server/);});
async function mount(t,projection=workspace){assert.equal(typeof module.mountTreasuryWorkspace,'function');const root=new Element();let live=structuredClone(session);const calls=[];const api={request:async(path,options={})=>{calls.push({path,options});return path.endsWith('/workspace')?projection:empty;}};const handle=module.mountTreasuryWorkspace({root,api,getSession:()=>live,confirmAction:()=>true});t.after(()=>handle());await handle.ready;return {root,calls,handle,revoke:()=>live={...live,permissions:[]}};}
test('all accepted staff actions have bounded editors while refresh keeps the same File and draft nodes',async t=>{const h=await mount(t);for(const action of actions)assert.ok(h.root.querySelector(`[data-treasury-action="${action}"]`),action);const form=h.root.querySelector('[data-treasury-action="opening_prepare"]'),amount=form.querySelector('[name="amount"]'),fileNode=h.root.querySelector('[data-treasury-evidence-file]');amount.value='120.00';const file=new Blob(['synthetic'],{type:'image/png'});fileNode.files=[file];await h.handle.refreshReadOnly();assert.equal(h.root.querySelector('[data-treasury-action="opening_prepare"]'),form);assert.equal(amount.value,'120.00');assert.equal(h.root.querySelector('[data-treasury-evidence-file]'),fileNode);assert.equal(fileNode.files[0],file);assert.equal(h.calls.filter(c=>c.options.method==='POST').length,0);});
test('delegated proof-only staff never loads private wallet history or balances',async t=>{const delegated={...workspace,capabilities:{claim_review:true},accounts:[{...workspace.accounts[0],actions:['claim_review'],balance:null}]};const h=await mount(t,delegated);await h.handle.activate('history');assert.equal(h.calls.some(c=>/\/(events|reconciliations)\?/.test(c.path)),false);assert.doesNotMatch(h.root.innerHTML,/90,071,992,547,409.93/);assert.match(h.root.innerHTML,/Private account history unavailable/);});
test('refreshed actor permissions tear down all private state before delayed content can render',async t=>{const h=await mount(t);h.revoke();await h.handle.refreshReadOnly();assert.equal(h.root.innerHTML,'');});
test('delegated claim review uses independent account-filtered claim endpoint',async t=>{const h=await mount(t,{...workspace,capabilities:{claim_review:true},accounts:[{...workspace.accounts[0],actions:['claim_review'],balance:null}]});await h.handle.activate('verify');assert.ok(h.calls.some(c=>c.path.includes('/claims?')&&c.path.includes('account_id='+account)));assert.equal(h.calls.some(c=>c.path.includes('/accounts/'+account+'/claims')),false);});
test('already aborted treasury mount performs no read and exposes no private editors',async()=>{const root=new Element(),controller=new AbortController();controller.abort();let calls=0;const handle=module.mountTreasuryWorkspace({root,api:{request:async()=>{calls++;}},getSession:()=>session,signal:controller.signal});await handle.ready;assert.equal(calls,0);assert.equal(root.innerHTML,'');});
test('drafts expose explicit reset without replacing sibling file nodes',async t=>{const h=await mount(t);const editor=h.root.querySelector('[data-treasury-action="opening_prepare"]'),node=h.root.querySelector('[data-treasury-evidence-file]'),amount=editor.querySelector('[name="amount"]');amount.value='120.00';const reset=editor.querySelector('[data-reset-draft]');assert.ok(reset);fire(reset,'click');assert.equal(amount.value,'');assert.equal(h.root.querySelector('[data-treasury-evidence-file]'),node);});

test('missing provider reference is an explicit unresolved owner observation, never guessed',()=>{assert.equal(typeof module.treasuryObservedReference,'function');assert.equal(module.treasuryObservedReference({reference:'',reference_unavailable:true},{owner:true,unclassified:true}),null);assert.throws(()=>module.treasuryObservedReference({reference:'',reference_unavailable:true},{owner:false,unclassified:true}),/owner/i);assert.throws(()=>module.treasuryObservedReference({reference:'',reference_unavailable:true},{owner:true,unclassified:false}),/unclassified|source/i);assert.throws(()=>module.treasuryObservedReference({reference:'',reference_unavailable:false},{owner:true,unclassified:true}),/reference/i);assert.equal(module.treasuryObservedReference({reference:'SYN-001',reference_unavailable:false},{owner:true,unclassified:true}),'SYN-001');});

test('Collector Excess is a lazy private task inside the existing Treasury workspace',async t=>{const h=await mount(t);assert.ok(h.root.querySelector('[data-task="surplus"]'));assert.equal(h.calls.some(c=>c.path.includes('/collector-surplus/')),false);await h.handle.activate('surplus');assert.ok(h.root.querySelector('[data-treasury-surplus]').querySelector('[data-private-panel]'));assert.ok(h.calls.some(c=>c.path.includes('/collector-surplus/workspace')));assert.match(h.root.textContent,/incomplete|unavailable|Collector/);});
