import test from 'node:test';
import assert from 'node:assert/strict';
const module=await import('../assets/treasury-api.js').catch(()=>({}));
const account='10000000-0000-4000-8000-000000000001',request='20000000-0000-4000-8000-000000000001',target='30000000-0000-4000-8000-000000000001';
const command={action:'opening_prepare',request_id:request,account_id:account,expected_version:1,amount:'0.00',cutoff:'2026-10-02T00:00:00Z',evidence_id:target,reason:'Synthetic count'};
const saved={contract_version:1,request_id:request,action:'opening_prepare',status:'saved',target_id:target,version:1,result:{actor_user_id:'owner',device_id:'device',account_id:account,ledger_context_id:target,opening:{id:target,version:1}}};
const workspace={contract_version:1,actor:{user_id:'owner',device_id:'device'},enabled:true,owner_configured:true,blockers:[],capabilities:{opening_prepare:true},claims:[],accounts:[{id:account,ledger_context_id:target,actions:['opening_prepare'],balance:null}]};
function session(){return {user:{id:'owner',role:'management',status:'active'},device_id:'device',device_registered:true,permissions:['treasury.view']};}
test('treasury decimal text preserves storage ceiling, zero count and rejects guessed precision',()=>{assert.equal(typeof module.requireTreasuryMoney,'function','exact money validation must exist');assert.equal(module.requireTreasuryMoney('9999999999999999.99'),'9999999999999999.99');assert.equal(module.requireTreasuryMoney('0.00'),'0.00');for(const value of [100,NaN,null,'100.001','1e2','01.00','-1.00'])assert.throws(()=>module.requireTreasuryMoney(value));assert.throws(()=>module.requireTreasuryMoney('0.00',{positive:true}));});
test('uncertain command can recover or explicitly replay only the frozen unchanged request',async()=>{assert.equal(typeof module.createTreasuryClient,'function','scoped treasury client must exist');let fail=true;const calls=[];const live=session();const client=module.createTreasuryClient({request:async(path,options={})=>{calls.push({path,options});if(path.endsWith('/workspace'))return workspace;if(path.includes('/requests/'))return null;if(fail)throw Object.assign(Error('Lost response'),{code:'network_uncertain'});return saved;}},{getSession:()=>live});await client.workspace();await assert.rejects(client.execute(command));command.reason='Later edit';assert.equal(client.state().status,'uncertain');await client.recover();assert.equal(client.state().status,'uncertain');await assert.rejects(client.execute({...command,request_id:target}));fail=false;const result=await client.retrySame();assert.equal(result.status,'saved');assert.equal(calls.filter(c=>c.options.method==='POST').length,2);assert.equal(calls.at(-1).options.body.reason,'Synthetic count');assert.equal(calls.at(-1).options.body.request_id,request);client.dispose();});
test('mismatched command result is uncertain and ordinary reads cannot unlock it',async()=>{assert.equal(typeof module.createTreasuryClient,'function');const client=module.createTreasuryClient({request:async(path)=>path.endsWith('/workspace')?workspace:({...saved,request_id:target})},{getSession:session});await client.workspace();await assert.rejects(client.execute({...command,reason:'Synthetic count'}),error=>error.code==='treasury_result_unverified');await client.workspace();assert.equal(client.state().status,'uncertain');client.dispose();});
test('offline commands make no POST and changed actor/device/permissions dispose pending private results',async()=>{assert.equal(typeof module.createTreasuryClient,'function');let live=session(),resolve;let posts=0;const client=module.createTreasuryClient({request:()=>{posts++;return new Promise(done=>resolve=done);}},{getSession:()=>live,isOnline:()=>false});await assert.rejects(client.execute(command),/internet|online/i);assert.equal(posts,0);client.dispose();const active=module.createTreasuryClient({request:path=>path.endsWith('/workspace')?Promise.resolve(workspace):new Promise(done=>resolve=done)},{getSession:()=>live});await active.workspace();const pending=active.execute(command);live={...live,permissions:[]};resolve(saved);await assert.rejects(pending,error=>error.code==='treasury_scope_changed');assert.equal(active.state().status,'disposed');});

test('claim uploads for own Client and assigned Collector use the same private metadata and byte-bound outcome',async()=>{
 const live=session();const uploadWorkspace={...workspace,capabilities:{claim_submit:true,claim_version:true,evidence_upload:true},accounts:[{...workspace.accounts[0],version:1,actions:['claim_submit','claim_version','evidence_upload']}]};const file=new Blob(['synthetic bytes'],{type:'image/png'});const digest=Buffer.from(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())).toString('hex');const metadata={request_id:request,account_id:account,account_version:1,client_id:target,loan_ids:[target],amount:'100.00',reference:'00001',claimed_at:'2026-10-02T00:00:00Z',sender_note:'Synthetic'};
 for(const role of ['client','collector']){const calls=[];const user={...live,user:{...live.user,role}};const client=module.createTreasuryClient({request:async(path,options={})=>{calls.push({path,options});if(path.endsWith('/workspace'))return uploadWorkspace;return {...saved,action:'claim_submit',result:{...saved.result,opening:undefined,claim:{id:target,account_id:account,client_id:target,version:1,status:'pending_verification',current_version:{version:1,sha256:digest,media_type:file.type,byte_count:file.size,amount:'100.00',reference:'00001',loan_ids:[target],account_version:1},history:[]}}};}},{getSession:()=>user});await client.workspace();assert.equal(typeof client.uploadClaim,'function');await client.uploadClaim(metadata,file);const call=calls.at(-1);assert.equal(call.path,'/api/v1/treasury/claims');assert.equal(call.options.rawBody,file);assert.deepEqual(JSON.parse(Buffer.from(call.options.headers['X-Treasury-Metadata'],'base64').toString('utf8')),metadata);assert.equal(call.options.headers['Content-Type'],'image/png');client.dispose();}
});
test('wrong uploaded content digest never confirms evidence as saved',async()=>{const uploadWorkspace={...workspace,capabilities:{evidence_upload:true},accounts:[{...workspace.accounts[0],actions:['evidence_upload']}]};const client=module.createTreasuryClient({request:async(path)=>path.endsWith('/workspace')?uploadWorkspace:{...saved,action:'evidence_upload',result:{...saved.result,opening:undefined,evidence:{id:target,account_id:account,media_type:'image/png',byte_count:3,sha256:'0'.repeat(64),purpose:'recipient'}}}},{getSession:session});await client.workspace();assert.equal(typeof client.uploadEvidence,'function');await assert.rejects(client.uploadEvidence({requestId:request,accountId:account,purpose:'recipient'},new Blob(['abc'],{type:'image/png'})),error=>error.code==='treasury_result_unverified');assert.equal(client.state().status,'uncertain');client.dispose();});
test('allocation preview rejects empty invented readiness and mismatched exact input',async()=>{const applyWorkspace={...workspace,accounts:[{...workspace.accounts[0],version:1,actions:['receipt_apply']}]};const input={expected_version:1,mode:'single',total_amount:'100.00',loans:[{loan_id:target,expected_version:1}],intent:'scheduled',covered_dates:[],extra_choice:null,regular_past_due_followup:null,effective_date:'2026-10-02'};const preview={contract_version:1,actor:workspace.actor,account_id:account,ledger_context_id:target,receipt_id:target,receipt_version:1,remaining_amount:'100.00',digest:'a'.repeat(64),mode:'single',total_amount:'100.00',effective_date:input.effective_date,loans:input.loans,allocations:[],blockers:[],can_apply:true};const client=module.createTreasuryClient({request:async(path)=>path.endsWith('/workspace')?applyWorkspace:preview},{getSession:session});await client.workspace();await assert.rejects(client.preview(target,input),error=>error.code==='treasury_result_unverified');client.dispose();});

test('every saved outcome matches actor, device, account, context, target and exact target version',async()=>{for(const change of [{result:{...saved.result,actor_user_id:'other'}},{result:{...saved.result,device_id:'other'}},{result:{...saved.result,account_id:target}},{result:{...saved.result,ledger_context_id:account}},{version:2},{target_id:account}]){const client=module.createTreasuryClient({request:async path=>path.endsWith('/workspace')?workspace:{...saved,...change}},{getSession:session});await client.workspace();await assert.rejects(client.execute({...command,reason:'Synthetic count'}),error=>error.code==='treasury_result_unverified');assert.equal(client.state().status,'uncertain');client.dispose();}});
test('private wallet history is never fetched for delegated proof-only access',async()=>{let history=0;const client=module.createTreasuryClient({request:async path=>{if(path.endsWith('/workspace'))return workspace;history++;return {items:[],total_count:0,limit:50,offset:0,has_more:false,totals:null};}},{getSession:session});await client.workspace();for(const kind of ['events','reconciliations'])await assert.rejects(client.list(kind,{accountId:account}),/private|unavailable/i);assert.equal(history,0);client.dispose();});
test('disabled and incompatible servers cannot start an action or show fabricated readiness',async()=>{for(const change of [{enabled:false},{contract_version:99}]){let posts=0;const client=module.createTreasuryClient({request:async(path,options={})=>{if(options.method==='POST')posts++;return {...workspace,...change};}},{getSession:session});if(change.contract_version)await assert.rejects(client.workspace(),/unavailable/i);else await client.workspace();await assert.rejects(client.execute(command));assert.equal(posts,0);client.dispose();}});
test('only reviewed unchanged server allocations can be applied without client arithmetic',async()=>{const applyWorkspace={...workspace,capabilities:{receipt_apply:true},accounts:[{...workspace.accounts[0],version:1,actions:['receipt_apply']}]};const input={expected_version:3,mode:'single',total_amount:'90071992547409.93',loans:[{loan_id:target,expected_version:7}],intent:'scheduled',covered_dates:['2026-10-02'],extra_choice:null,regular_past_due_followup:null,effective_date:'2026-10-02'};const preview={contract_version:1,actor:workspace.actor,account_id:account,ledger_context_id:target,receipt_id:target,receipt_version:3,remaining_amount:'90071992547410.00',digest:'a'.repeat(64),mode:input.mode,total_amount:input.total_amount,effective_date:input.effective_date,loans:input.loans,allocations:[{loan_id:target,loan_type:'regular',component:'scheduled',amount:input.total_amount,applied_amount:input.total_amount,unallocated_amount:'0.00',covered_dates:input.covered_dates,intent:input.intent}],blockers:[],can_apply:true};let posts=0;const client=module.createTreasuryClient({request:async(path,options)=>{if(path.endsWith('/workspace'))return applyWorkspace;if(path.endsWith('/allocation-preview'))return preview;posts++;return {...saved,action:'receipt_apply',result:{...saved.result,opening:undefined,receipt:{id:target,version:1,remaining_amount:'0.07'}}};}},{getSession:session});await client.workspace();await client.preview(target,input);const body={...input,request_id:request,account_id:account,action:'receipt_apply',receipt_id:target,digest:preview.digest};await assert.rejects(client.execute({...body,total_amount:'90071992547409.94'}),/preview/i);await assert.rejects(client.execute({...body,expected_version:1}),/preview/i);assert.equal(posts,0);const result=await client.execute(body);assert.equal(result.result.receipt.remaining_amount,'0.07');assert.equal(posts,1);client.dispose();});

test('hash preparation owns the write guard before a second command can start',async()=>{let release,posts=0;const file={type:'image/png',size:3,arrayBuffer:()=>new Promise(done=>release=done)};const both={...workspace,capabilities:{opening_prepare:true,evidence_upload:true},accounts:[{...workspace.accounts[0],actions:['opening_prepare','evidence_upload']}]};const client=module.createTreasuryClient({request:async(path,options={})=>{if(path.endsWith('/workspace'))return both;posts++;return saved;}},{getSession:session});await client.workspace();const upload=client.uploadEvidence({requestId:target,accountId:account},file).catch(()=>null);await new Promise(resolve=>setTimeout(resolve,0));await assert.rejects(client.execute(command),/pending|recover/i);assert.equal(posts,0);release(new TextEncoder().encode('abc').buffer);await upload;client.dispose();});

test('claim-only account projection need not disclose its private ledger context',async()=>{const ownWorkspace={...workspace,capabilities:{claim_submit:true},accounts:[{id:account,version:1,actions:['claim_submit'],balance:null}]};const file=new Blob(['abc'],{type:'image/png'});const sha256=Buffer.from(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())).toString('hex');const metadata={request_id:request,account_id:account,account_version:1,client_id:target,loan_ids:[target],amount:'1.00',reference:'0001',claimed_at:'2026-10-02T00:00:00Z'};const claim={id:target,version:1,account_id:account,client_id:target,current_version:{version:1,sha256,media_type:file.type,byte_count:file.size,loan_ids:[target],amount:'1.00',reference:'0001',account_version:1}};const client=module.createTreasuryClient({request:async path=>path.endsWith('/workspace')?ownWorkspace:{...saved,action:'claim_submit',result:{...saved.result,opening:undefined,claim}}},{getSession:session});await client.workspace();assert.equal((await client.uploadClaim(metadata,file)).status,'saved');client.dispose();});

test('adding an authorized account preserves the existing mount while revoked scope disposes it',async()=>{let projection=workspace;const client=module.createTreasuryClient({request:async()=>projection},{getSession:session});await client.workspace();projection={...workspace,accounts:[...workspace.accounts,{...workspace.accounts[0],id:request}]};await client.workspace();assert.equal(client.isCurrent(),true);projection={...workspace,accounts:[]};await assert.rejects(client.workspace(),error=>error.code==='treasury_scope_changed');assert.equal(client.state().status,'disposed');});

test('a saved command cannot be confirmed by an unrelated entity kind',async()=>{const client=module.createTreasuryClient({request:async p=>p.endsWith('/workspace')?workspace:{...saved,result:{...saved.result,opening:undefined,claim:{id:target,version:1}}}},{getSession:session});await client.workspace();await assert.rejects(client.execute(command),e=>e.code==='treasury_result_unverified');assert.equal(client.state().status,'uncertain');client.dispose();});
