import test from 'node:test';import assert from 'node:assert/strict';
import {Element,fire} from './helpers/dom.mjs';
const module=await import('../assets/treasury-payment-claim.js').catch(()=>({}));
const account='10000000-0000-4000-8000-000000000001',client='20000000-0000-4000-8000-000000000001',loan='30000000-0000-4000-8000-000000000001';
const session={user:{id:'owner',role:'client',status:'active'},device_id:'device',device_registered:true,permissions:[]};
const workspace={contract_version:1,actor:{user_id:'owner',device_id:'registered'},enabled:true,owner_configured:true,blockers:[],capabilities:{claim_submit:true,claim_version:true},accounts:[{id:account,ledger_context_id:loan,version:1,alias:'Synthetic receiving',actions:['claim_submit','claim_version'],balance:null}],claims:[]};
const instructions={items:[{account_id:account,account_version:1,alias:'Synthetic receiving',kind:'gcash',currency:'PHP',payment_instructions:'Synthetic recipient only'}],total_count:1};
const listing={items:[],total_count:0,limit:50,offset:0,has_more:false,totals:null};
const tick=()=>new Promise(resolve=>setTimeout(resolve,5));
async function mount(t,{mutation,workspaceLoader=()=>workspace,listingLoader=()=>listing}={}){assert.equal(typeof module.mountTreasuryClaim,'function','own and assigned claim editor must exist');const root=new Element();const calls=[];let live=structuredClone(session);const api={request:async(path,options={})=>{calls.push({path,options});if(options.method==='POST')return mutation?.(path,options);if(path.endsWith('/workspace'))return workspaceLoader();if(path.endsWith('/instructions'))return instructions;return listingLoader(path);}};const handle=module.mountTreasuryClaim({root,api,getSession:()=>live,borrowerContext:{client_id:client,loans:[{loan_id:loan,loan_number:'Own loan'}]}});t.after(()=>handle());await handle.ready;return {root,calls,handle,changeAuthority:()=>live={...live,user:{...live.user,id:'different'}}};}
test('own claim view never asks for wallet events, balances or reconciliation',async t=>{const h=await mount(t);assert.match(h.root.innerHTML,/Synthetic recipient only/);assert.doesNotMatch(h.root.innerHTML,/expected balance|wallet history|opening position/i);assert.equal(h.calls.some(c=>/\/accounts\/.*\/(events|receipts|reconciliations)/.test(c.path)),false);});
test('read refresh retains exact editor node, selected File and unrelated text',async t=>{const h=await mount(t);const form=h.root.querySelector('[data-treasury-claim-form]'),fileNode=form.querySelector('[name="proofFile"]'),note=form.querySelector('[name="sender_note"]');const file=new Blob(['synthetic'],{type:'image/png'});fileNode.files=[file];note.value='Retain draft';await h.handle.refreshReadOnly();assert.equal(h.root.querySelector('[data-treasury-claim-form]'),form);assert.equal(form.querySelector('[name="proofFile"]'),fileNode);assert.equal(fileNode.files[0],file);assert.equal(note.value,'Retain draft');assert.equal(h.calls.filter(c=>c.options.method==='POST').length,0);});
test('uncertain claim upload stays locked through read refresh with original File and metadata',async t=>{let posts=0;const h=await mount(t,{mutation:()=>{posts++;throw Object.assign(Error('Lost upload response'),{code:'network_uncertain'});}});const form=h.root.querySelector('[data-treasury-claim-form]');for(const [name,value]of Object.entries({account_id:account,loan_id:loan,amount:'100.00',reference:'000001',claimed_at:'2026-10-02T08:00',sender_note:'Retain note'}))form.querySelector(`[name="${name}"]`).value=value;const file=new Blob(['synthetic'],{type:'image/png'});form.querySelector('[name="proofFile"]').files=[file];fire(form,'submit');await tick();await h.handle.refreshReadOnly();fire(form,'submit');await tick();assert.equal(posts,1);assert.equal(form.querySelector('[name="proofFile"]').files[0],file);assert.equal(form.querySelector('[name="sender_note"]').value,'Retain note');assert.equal(h.handle.isWritePending(),true);});
test('changed authority cannot show late private claim results',async t=>{let release;const h=await mount(t,{listingLoader:()=>listing});const original=h.handle.refreshReadOnly;const pending=h.handle.refreshReadOnly();h.changeAuthority();await pending;await h.handle.refreshReadOnly();assert.equal(h.root.innerHTML,'');});

test('already aborted claim mount does not read, render or register controls',()=>{const root=new Element();const controller=new AbortController();controller.abort();let calls=0;assert.doesNotThrow(()=>module.mountTreasuryClaim({root,api:{request(){calls++;}},getSession:()=>session,signal:controller.signal,borrowerContext:{client_id:client,loans:[]}}));assert.equal(calls,0);assert.equal(root.innerHTML,'');});

test('live account grant revocation removes all retained claim drafts and private history',async t=>{let projection=workspace;const h=await mount(t,{workspaceLoader:()=>projection});h.root.querySelector('[name="sender_note"]').value='Private retained note';projection={...workspace,accounts:[{...workspace.accounts[0],actions:[]}],capabilities:{claim_submit:false,claim_version:false}};await h.handle.refreshReadOnly();assert.equal(h.root.innerHTML,'');});
